microsoft/botbuilder-python

libraries/botframework-connector/tests/test_attachments.py, libraries/botframework-connector/tests/test_auth.py, libraries/botframework-connector/tests/test_conversations.py
Removed `microsoft.` from `microsoft.botbuilder.schema` so that the imports properly work.
To run these tests, users must do the following:
1. enter `pip install -r requirements.txt`
2. enter `pytest` which will then run the tests. There should be 28 tests run.
=> update botframework-connector tests to reference new namespaced packages

.cache/v/cache/lastfailed, .travis.yml, libraries/botbuilder-azure/.cache/v/cache/lastfailed, libraries/botbuilder-azure/botbuilder/azure/__init__.py, libraries/botbuilder-azure/botbuilder/azure/about.py, libraries/botbuilder-azure/botbuilder/azure/cosmosdb_storage.py, libraries/botbuilder-azure/setup.py, libraries/botbuilder-azure/tests/test_cosmos_storage.py, samples/EchoBot-with-CosmosState/EchoBot-with-CosmosState.bot, samples/EchoBot-with-CosmosState/README.md, samples/EchoBot-with-CosmosState/main.py, samples/EchoBot-with-CosmosState/requirements.txt, samples/EchoBot-with-CosmosState/sample_credentials_file.json
Hi all, 
I created a middleware package for talking with CosmosDB from the Python Bot Framework, I used a similar structure with a botbuilder-azure package. It includes a config object and a storage object, as well as tests for the integration. In the samples folder is a adaptation of the EchoBot that talks with Cosmos instead of memory storage. Automated testing will rely on CosmosDB emulator running, this is the same as with the Node version of the CosmosDB storage.
- botbuilder-azure/botbuilder/azure/cosmosdb_storage.py - main code for using Cosmos as a middleware
- botbuilder-azure/tests/test_cosmos_storage.py - tests for the middleware
- samples/Echobot-with-CosmosState/* - sample that uses the middleware
=> Azure CosmosDbStorage Middleware

libraries/botbuilder-applicationinsights/tests/test_telemetry_waterfall.py
Fix waterfall test.  
The DialogState was not being set() (via accessor) before the storage save occurred.
=> Fix waterfall test (add accessor set)

libraries/botbuilder-applicationinsights/botbuilder/applicationinsights/__init__.py, libraries/botbuilder-applicationinsights/botbuilder/applicationinsights/application_insights_telemetry_client.py, libraries/botbuilder-applicationinsights/botbuilder/applicationinsights/django/__init__.py, libraries/botbuilder-applicationinsights/botbuilder/applicationinsights/django/bot_telemetry_middleware.py, libraries/botbuilder-applicationinsights/botbuilder/applicationinsights/integration_post_data.py, libraries/botbuilder-applicationinsights/django_tests/README.md, libraries/botbuilder-applicationinsights/django_tests/all_tests.sh, libraries/botbuilder-applicationinsights/django_tests/run_test.sh, libraries/botbuilder-applicationinsights/django_tests/template.html, libraries/botbuilder-applicationinsights/django_tests/tests.py, libraries/botbuilder-applicationinsights/django_tests/urls.py, libraries/botbuilder-applicationinsights/django_tests/views.py, libraries/botbuilder-applicationinsights/setup.py
From the README:
Django generates *code* to create projects (`django-admin startproject`) and apps.  For testing, we test the generated code.  The tests are bare-bones to be compatible across different versions of django.
- This project contains a script to execute tests against currently supported version(s) of python and django.
- Assume latest version of Application Insights.
- Relies on virtualenv to run all tests.
- Uses django commands to generate new project and execute django tests.
- To run, first `cd django_tests` and then `bash .\all_tests.sh` (ie, in Powershell) to run all permutations.
File | Description
--- | ---
all_tests.sh | Runs our current test matrix of python/django versions.  Current matrix is python (3.6) and django (2.2). 
README.md | This file.
run_test.sh | Runs …
=> Add Application Insights Django-specific tests

README.md
The link doesn't work (because of the org "rename") but also the last build against Travis CI was over 2 months ago; and Azure Dev Ops is setup.
=> remove Travis CI badge from README.md

README.md, libraries/botbuilder-applicationinsights/README.rst, libraries/botbuilder-core/README.rst, libraries/botbuilder-dialogs/README.rst, libraries/botbuilder-schema/README.rst, libraries/botframework-connector/README.rst, samples/Core-Bot/bots/dialog_bot.py
fixed package badge naming from botframework-applicationinsights to botbuilder-applicationinsights, also updated the azure devops links given that the name of the pipeline was changed
=> Fixed READMEs

libraries/botbuilder-ai/botbuilder/ai/qna/qnamaker.py, libraries/botbuilder-ai/tests/qna/test_data/NoAnswerFoundInKb.json, libraries/botbuilder-ai/tests/qna/test_qna.py
Fixes issue #179 
* When QnAMaker API returns "`No good match found in KB.`", it will be filtered properly now in `QnAMaker._format_qna_results()`.
* Added unit test for "No good match found in KB" case
=> Telemetry emits correct EventData for "No Answer Found in KB" case

libraries/botbuilder-core/botbuilder/core/bot_adapter.py, libraries/botbuilder-core/botbuilder/core/bot_framework_adapter.py, libraries/botbuilder-core/tests/test_bot_framework_adapter.py, libraries/botbuilder-schema/botbuilder/schema/_models.py, libraries/botbuilder-schema/botbuilder/schema/_models_py3.py
Added middleware to address transitional location of tenant_id field for teams in BotFrameworkAdapter. More testing on adapter pending.
*This PR address issues #139 and #140
=> Added middleware to address transitional location of tenant_id field 

libraries/botbuilder-ai/botbuilder/ai/luis/luis_recognizer.py, libraries/botbuilder-ai/tests/luis/luis_recognizer_test.py
Fixes: #206
Add ability for user to pass luis prediction options into 'Recognizer.recognize' function. Whatever fields are present should override what was set previously via constructor to 'Recognizer._options', for the duration of the request.
=> 206 add luis prediction options to recognizer

.gitignore, samples/python-flask/13.core-bot/main.py, samples/python-flask/13.core-bot/requirements.txt
- Adds `venv*/` to `.gitignore`
- Removes `asyncio` from flask core-bot's requirements.txt (this is a core module and `asyncio` on PyPI is only relevant for Python 3.3 which doesn't include `asyncio` in its stdlib.
- Minor cleanup in flask core-bot's `main.py`
=> update .gitignore, remove asyncio from flask core-bot requirements

samples/django/13.core-bot/bots/bots.py, samples/django/13.core-bot/bots/views.py
- `async` fix in `aux_func` for Django
- Move `loop` to be global
=> Fix django async/loop

libraries/botbuilder-core/botbuilder/core/bot_state.py, libraries/botbuilder-core/botbuilder/core/conversation_state.py, libraries/botbuilder-core/botbuilder/core/memory_storage.py, libraries/botbuilder-core/botbuilder/core/user_state.py, libraries/botbuilder-core/tests/test_bot_state.py
Added missing tests with some bug fixes
fixes #146
=> added missing BotState tests and some state fixes

libraries/botbuilder-dialogs/botbuilder/dialogs/prompts/datetime_prompt.py, libraries/botbuilder-dialogs/botbuilder/dialogs/prompts/number_prompt.py, libraries/botbuilder-dialogs/tests/test_dateTime_prompt.py, libraries/botbuilder-dialogs/tests/test_number_prompt.py
- Add a new test for **DateTimePrompt** using _Recognizers-Text.DateTime_.
- Add a new test for **NumberPrompt** using _Recognizers-Text.Number_.
- Minor fixes on **NumberPrompt** class to use _recognize_number_ method (replaced ChoiceRecognizer with NumberRecognizer for parity with DotNet implementation).
We ran all tests locally, also, we configured an Azure Pipeline to automatically run the tests.
_Note: It's necessary to update the Recognizers-Text-Number package with the fix made in PR# 1554 of Recognizers-Text_
1. Add a **_Use Python_** task. Configure it to use the latest version of python.
2. Add a **_Command Line_** task to run all the test in the botbuilder-libraries.
The script used is:
```Powershell
pip install -e ./libraries/botbuilder-schema
pip install -e …
```
=> Add tests for DateTimePrompt and NumberPrompt

libraries/botbuilder-dialogs/botbuilder/dialogs/prompts/oauth_prompt.py
Oauth prompt should default the input hint to accepting_input not expecting_input
=> fix for accepting_input

libraries/botbuilder-dialogs/botbuilder/dialogs/prompts/choice_prompt.py, libraries/botbuilder-dialogs/botbuilder/dialogs/prompts/prompt.py, libraries/botbuilder-dialogs/tests/test_choice_prompt.py
Fixes #239 , #240 
* `ChoicePrompt._default_choice_options` now specifies **`inline_or_more`** for the `ChoiceFactoryOptions` in the appropriate culture
* `Prompt` was previously trying to use `Dict.get()` method, but with the enum class as the key instead of the _**value**_ that the enum equated to, making all styles go to "default" `ListStyle` previously, when key was not found (in this case `in_line` styling)
* now properly uses enum value as key
* rearranged `switcher` variable to properly map in the same order as the values in `ListStyle` enum class, to apply correct styling
* `ListStyle.none` also now returns as an `ActivityType.message`, whereas before it was `None`
* updated unit tests to not only check for `in_line` styling
=> ChoicePrompt properly uses ListStyle that's specified

libraries/botbuilder-dialogs/botbuilder/dialogs/choices/choice_factory.py, libraries/botbuilder-dialogs/botbuilder/dialogs/prompts/confirm_prompt.py, libraries/botbuilder-dialogs/botbuilder/dialogs/prompts/prompt.py, libraries/botbuilder-dialogs/setup.py, libraries/botbuilder-dialogs/tests/test_confirm_prompt.py
- Updated recognizers
- Confirm prompt working with tests
- Fix in Prompt class in append_choices
- Fix in ChoiceFactory in inline
=> Recognizers versions updated, confirm prompt now working with tests

samples/Core-Bot/adapter_with_error_handler.py, samples/Core-Bot/dialogs/booking_dialog.py
Adding confirm prompt to Core Bot and fix on that sample error handling.
=> Adding confirm prompt to Core Bot and fix on that sample error handling

libraries/botbuilder-core/botbuilder/core/activity_handler.py, libraries/botbuilder-core/tests/test_activity_handler.py
=> Message reaction in activity handler

libraries/botbuilder-core/botbuilder/core/__init__.py, libraries/botbuilder-core/botbuilder/core/show_typing_middleware.py, libraries/botbuilder-core/tests/test_show_typing_middleware.py
Typing middleware implemented
fixes #286
=> TypingMiddleware

libraries/botbuilder-applicationinsights/botbuilder/applicationinsights/application_insights_telemetry_client.py, libraries/botbuilder-core/botbuilder/core/__init__.py, libraries/botbuilder-core/botbuilder/core/bot_telemetry_client.py, libraries/botbuilder-core/botbuilder/core/null_telemetry_client.py
=> Added SeverityEnum

libraries/botbuilder-core/botbuilder/core/__init__.py, libraries/botbuilder-core/botbuilder/core/private_conversation_state.py, libraries/botbuilder-core/tests/test_private_conversation_state.py
PrivateConversationState implemented with basic unit test, more testing pending.
fixes #145
=> PrivateConversationState 

libraries/botbuilder-core/botbuilder/core/turn_context.py, libraries/botbuilder-core/tests/test_turn_context.py
Mention support and get_reply_conversation_reference added to TurnContext
fixes #273
=> Mentions support in TurnContext

libraries/botbuilder-core/botbuilder/core/__init__.py, libraries/botbuilder-core/botbuilder/core/middleware_set.py, libraries/botbuilder-core/botbuilder/core/telemetry_constants.py, libraries/botbuilder-core/botbuilder/core/telemetry_logger_constants.py, libraries/botbuilder-core/botbuilder/core/telemetry_logger_middleware.py, libraries/botbuilder-core/tests/test_telemetry_middleware.py
Initial port of Telemetry Middleware.
=> Telemetry Middleware

libraries/botbuilder-core/botbuilder/core/__init__.py, libraries/botbuilder-core/botbuilder/core/memory_transcript_store.py, libraries/botbuilder-core/botbuilder/core/transcript_logger.py, libraries/botbuilder-core/tests/test_memory_transcript_store.py, libraries/botbuilder-core/tests/test_private_conversation_state.py, libraries/botbuilder-core/tests/test_show_typing_middleware.py
=> Add Transcript

samples/13.core-bot/dialogs/date_resolver_dialog.py, samples/13.core-bot/dialogs/main_dialog.py, samples/13.core-bot/helpers/luis_helper.py
Fixes #292 
___
**Issue:**
* In [C#](https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/13.core-bot/Dialogs/DateResolverDialog.cs#L53) and [JS](https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/javascript_nodejs/13.core-bot/dialogs/dateResolverDialog.js#L43) CoreBots, the logic to test for if the datetime entity parsed should check if it **is ambigous** still => then if it is ambigous, reprompt user for definitive datetime value
* However in Python its test incorrectly checks if the datetime **is definitive instead of ambigous**
This PR corrects the conditional logic for ambigous datetimes parsed from user when booking a flight.
* `LuisHelper` class parsed values for location entities (the `Origin` and `Destination` of the flight), …
=> Fix Date Resolver in CoreBot

libraries/botbuilder-dialogs/botbuilder/dialogs/prompts/number_prompt.py, libraries/botbuilder-dialogs/tests/test_number_prompt.py
Fixes #281 
___
Originally retry prompts were not sending to the user when an invalid value was sent to a `NumberPrompt` (e.g. "Please enter a number" "hello" <-- invalid)
* This was happening simply because `NumberPrompt` was missing an "`await`" for sending an activity if it passed the condition of needing to send a retry prompt.
* Uncommented tests that were previously ported that were breaking for retry promps and validation
Expected Behavior (plugging a `NumberPrompt` into CoreBot real quickly)
=> Fixed retry prompting in NumberPrompt by adding await

samples/python_django/13.core-bot/bots/settings.py
Change `SECRET_KEY` to make it clearer it needs to change.
=> Change secret key so it's clearer that it needs to be changed

samples/45.state-management/bots/state_management_bot.py
Fixes #306 
___
Added "`To see conversation data, type anything.`" in `45.state-management/bots/state_management_bot.py` for parity with C# sample as the "golden standard" sample.
=> Sample 45 - Changed greeting to include instructions to type anything to see state

libraries/botbuilder-ai/botbuilder/ai/qna/models/generate_answer_request_body.py, libraries/botbuilder-ai/botbuilder/ai/qna/models/qnamaker_trace_info.py, libraries/botbuilder-ai/botbuilder/ai/qna/qnamaker_options.py, libraries/botbuilder-ai/botbuilder/ai/qna/utils/generate_answer_utils.py, libraries/botbuilder-ai/tests/qna/test_qna.py
Addition of a new optional parameter (qnaId) in GenerateAnswer body.
- Support for QnA Id added 
Test case added
=> [QnA Maker] Multi-turn SDK support for QnAId 

libraries/botbuilder-core/botbuilder/core/bot_framework_adapter.py, libraries/botbuilder-core/tests/test_bot_framework_adapter.py
Parity:
* https://github.com/microsoft/botbuilder-dotnet/pull/2481
* https://github.com/microsoft/botbuilder-js/pull/1173
Keeps tentant_id & channel_data in create_conversation
**I'm not confident I wrote the test appropriately. It works, but I'm not sure I went about it the best way.** Let me know if you'd like something changed.
**Before Change**
**After Change**
=> [Parity w/ Dotnet] create_conversation tentant_id/channel_data

samples/06.using-cards/app.py, samples/13.core-bot/app.py, samples/21.corebot-app-insights/main.py, samples/45.state-management/app.py, samples/experimental/101.corebot-bert-bidaf/bot/main.py, samples/python_django/13.core-bot/bots/views.py
Fixes: https://github.com/microsoft/botbuilder-python/issues/312
**Issue Summary**
`request.headers["Content-Type"]` sometimes comes in as 
```
application/json; charset=utf-8
````
...which causes the `415: UnsupportedMediaType` to throw.
**Changes**
In `app.py` for the samples, it implements this diff:
```diff
@app.route("/api/messages", methods=["POST"])
def messages():
"""Main bot message handler."""
-   if request.headers["Content-Type"] == "application/json":
+   if "application/json" in request.headers["Content-Type"]:
body = request.json
else:
return Response(status=415)
```
=> Fix UnsupportedMediaType in samples

libraries/botbuilder-ai/botbuilder/ai/luis/luis_recognizer.py, libraries/botbuilder-core/botbuilder/core/recognizer.py
=> Adding Recognizer interface to LuisRecognizer

libraries/botbuilder-core/botbuilder/core/adapters/test_adapter.py, libraries/botbuilder-core/botbuilder/core/bot_state.py, libraries/botbuilder-core/botbuilder/core/inspection/__init__.py, libraries/botbuilder-core/botbuilder/core/inspection/inspection_middleware.py, libraries/botbuilder-core/botbuilder/core/inspection/inspection_session.py, libraries/botbuilder-core/botbuilder/core/inspection/inspection_sessions_by_status.py, libraries/botbuilder-core/botbuilder/core/inspection/inspection_state.py, libraries/botbuilder-core/botbuilder/core/inspection/interception_middleware.py, libraries/botbuilder-core/botbuilder/core/inspection/trace_activity.py, libraries/botbuilder-core/botbuilder/core/state_property_accessor.py, libraries/botbuilder-core/setup.py, libraries/botbuilder-core/tests/requirements.txt, libraries/botbuilder-core/tests/test_inspection_middleware.py
Inspection Middleware leveraging jsonpickle.
fixes #334
=> Inspection middleware with jsonpickle

libraries/botbuilder-core/botbuilder/core/adapters/test_adapter.py, libraries/botbuilder-testing/README.rst, libraries/botbuilder-testing/botbuilder/testing/__init__.py, libraries/botbuilder-testing/botbuilder/testing/about.py, libraries/botbuilder-testing/botbuilder/testing/dialog_test_client.py, libraries/botbuilder-testing/botbuilder/testing/dialog_test_logger.py, libraries/botbuilder-testing/requirements.txt, libraries/botbuilder-testing/setup.py, libraries/botbuilder-testing/tests/test_dialog_test_client.py
* dialog test client
* dialog test logger
* unit tests.
More descriptions are in #198 .
=> DialogTestClient for Py

libraries/botbuilder-core/botbuilder/core/turn_context.py, libraries/botbuilder-core/tests/test_turn_context.py
Fixes https://github.com/microsoft/botbuilder-dotnet/issues/2388
Parity with .NET and Node.js
=> Apply conversation reference in TurnContext.update_activity

libraries/botbuilder-core/botbuilder/core/turn_context.py, libraries/botbuilder-core/tests/test_turn_context.py
Parity with https://github.com/microsoft/botbuilder-js/pull/1355
=> Added trace activity helper in turn context

libraries/botbuilder-core/botbuilder/core/turn_context.py, libraries/botbuilder-core/tests/test_turn_context.py
* Apply conversation reference in TurnContext.update_activity
* Trace activity helper in turn context
=> Merge master into 4.5.0b5

libraries/botbuilder-ai/botbuilder/ai/luis/luis_util.py, libraries/botbuilder-ai/botbuilder/ai/qna/utils/active_learning_utils.py, libraries/botbuilder-azure/tests/test_blob_storage.py, libraries/botbuilder-azure/tests/test_cosmos_storage.py, libraries/botbuilder-azure/tests/test_key_validation.py, libraries/botbuilder-core/botbuilder/core/inspection/trace_activity.py, libraries/botbuilder-core/tests/test_auto_save_middleware.py, libraries/botbuilder-core/tests/test_bot_adapter.py, libraries/botbuilder-core/tests/test_inspection_middleware.py, libraries/botbuilder-core/tests/test_memory_storage.py, libraries/botbuilder-core/tests/test_show_typing_middleware.py, libraries/botbuilder-core/tests/test_test_adapter.py, libraries/botbuilder-core/tests/test_turn_context.py, libraries/botbuilder-dialogs/botbuilder/dialogs/choices/channel.py, libraries/botbuilder-dialogs/botbuilder/dialogs/prompts/confirm_prompt.py, libraries/botbuilder-dialogs/tests/test_choice_prompt.py, libraries/botbuilder-dialogs/tests/test_waterfall.py, libraries/botframework-connector/tests/test_auth.py, libraries/botframework-connector/tests/test_conversations.py, libraries/botframework-connector/tests/test_conversations_async.py
Compliance with new version of black
=> Update black formatting

libraries/functional-tests/functionaltestbot/Dockfile, libraries/functional-tests/functionaltestbot/flask_bot_app/__init__.py, libraries/functional-tests/functionaltestbot/flask_bot_app/app.py, libraries/functional-tests/functionaltestbot/flask_bot_app/bot_app.py, libraries/functional-tests/functionaltestbot/flask_bot_app/default_config.py, libraries/functional-tests/functionaltestbot/flask_bot_app/my_bot.py, libraries/functional-tests/functionaltestbot/requirements.txt, libraries/functional-tests/functionaltestbot/runserver.py, libraries/functional-tests/tests/direct_line_client.py, libraries/functional-tests/tests/test_py_bot.py
* docker file with py 3.7.
* echo bot for flask.
* test with direct line client.
This is for functional test.
=> Dockerfile for Flask bot

libraries/botframework-connector/botframework/connector/auth/microsoft_app_credentials.py
=> Session injection supported

samples/02.echo-bot/app.py, samples/02.echo-bot/deploymentTemplates/template-with-preexisting-rg.json
- Rename flask `APP` to `app` to utilize Azure's [automated flask `app:app` detection](https://docs.microsoft.com/en-us/azure/app-service/containers/how-to-configure-python#flask-app)
- Add ARM template with Linux App Service and Linux App Service Plan provisioning
- **Note:** The ARM template automatically configures kudu to [build on deployment](https://github.com/projectkudu/kudu/wiki/Configurable-settings#enabledisable-build-actions), which differs from the Node.js model where the developer is expected to include their local `node_modules/`
The commands used to deploy with this ARM template mirror the steps found in the docs page: "[**Deploy your bot**](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp#deploy-code-to-azu …
=> [Deployment] Modify echo-bot to work out of the box w/ new ARM template

samples/18.bot-authentication/README.md, samples/18.bot-authentication/app.py, samples/18.bot-authentication/bots/__init__.py, samples/18.bot-authentication/bots/auth_bot.py, samples/18.bot-authentication/bots/dialog_bot.py, samples/18.bot-authentication/config.py, samples/18.bot-authentication/deploymentTemplates/template-with-preexisting-rg.json, samples/18.bot-authentication/dialogs/__init__.py, samples/18.bot-authentication/dialogs/logout_dialog.py, samples/18.bot-authentication/dialogs/main_dialog.py, samples/18.bot-authentication/helpers/__init__.py, samples/18.bot-authentication/helpers/dialog_helper.py, samples/18.bot-authentication/requirements.txt
Used the ARM template and app.py pattern that Steven pushed.
Future task will be to standardize this (and other) samples on whatever our final deploy solution is.
=> Added 18.bot-authentication

libraries/botbuilder-azure/botbuilder/azure/cosmosdb_partitioned_storage.py, libraries/botbuilder-azure/botbuilder/azure/cosmosdb_storage.py
Fixes: https://github.com/microsoft/botbuilder-dotnet/issues/2766
and
https://github.com/microsoft/botbuilder-dotnet/issues/2765
NOTE: CosmosDbPartitionedConfig defaults compatibility_mode to false, since this library has NOT been released yet.  (dotnet and javascript are defaulted to true, since they have already been released)
Still need to add some tests.
Also, the pattern is odd where we let self.client.CreateDatabase error then try self.client.ReadDatabase ... this seems like it should be switched.
=> Add keysuffix and compat mode to cosmosdbpartitionedstorage

libraries/botbuilder-azure/botbuilder/azure/blob_storage.py, libraries/botbuilder-azure/botbuilder/azure/cosmosdb_partitioned_storage.py, libraries/botbuilder-azure/botbuilder/azure/cosmosdb_storage.py, libraries/botbuilder-core/botbuilder/core/memory_storage.py
Fixes instances where `item.get("e_tag")` fails due to item not being a dict, but having the "e_tag" attribute. Also changed a few instances where this was working fine to match the new "style" of this fix:
```python
e_tag = None
if isinstance(item, dict):
e_tag = item.get("e_tag", None)
elif hasattr(item, "e_tag"):
e_tag = item.e_tag
```
All current tests pass (with EMULATOR_RUNNING = True, of course)
=> Storage attr fix

libraries/botbuilder-core/botbuilder/core/teams/teams_info.py
Access _credentials from turn_context adapter when creating teams connector client
=> Cherry pick connector client creation cleanup to 4.7

libraries/botbuilder-dialogs/botbuilder/dialogs/prompts/prompt.py
=> mm-api-ref-docs-prompt

libraries/botbuilder-core/botbuilder/core/conversation_state.py
=> mm-api-ref-docs-conversation-state

libraries/botbuilder-core/botbuilder/core/activity_handler.py
=> mm-api-ref-docs-activity-handler

libraries/botbuilder-core/botbuilder/core/bot_framework_adapter.py
Added ref documentation (WIP).
=> mm-api-ref-docs-adapter

libraries/botbuilder-dialogs/botbuilder/dialogs/prompts/prompt_options.py
=> mm-api-ref-docs-prompt-options

libraries/botbuilder-dialogs/botbuilder/dialogs/prompts/oauth_prompt.py
=> mm-api-ref-docs-oauth-prompt

libraries/botbuilder-core/botbuilder/core/conversation_state.py
Added reference documentation. 
Recreate PR to conform to the creation of "draft pull request".
=> mm-api-ref-docs-conversationstate

libraries/botbuilder-core/botbuilder/core/bot_state.py, libraries/botbuilder-dialogs/botbuilder/dialogs/prompts/prompt.py
Indented .. note:: content.
Replaced :method: with :meth:
=> mm-api-ref-style-issues-fixes

libraries/botbuilder-ai/botbuilder/ai/about.py, libraries/botbuilder-applicationinsights/botbuilder/applicationinsights/about.py, libraries/botbuilder-azure/botbuilder/azure/about.py, libraries/botbuilder-core/botbuilder/core/about.py, libraries/botbuilder-core/botbuilder/core/integration/aiohttp_channel_service_exception_middleware.py, libraries/botbuilder-core/setup.py, libraries/botbuilder-dialogs/botbuilder/dialogs/about.py, libraries/botbuilder-schema/setup.py, libraries/botbuilder-testing/botbuilder/testing/about.py, libraries/botframework-connector/setup.py
Sets the version to 4.7.1 in the various about.py or setup.py so that "pip -e" commands work as expected.
=> Sets version on Python libs

libraries/botbuilder-core/botbuilder/core/bot_framework_adapter.py
=> continue conversation fix for skills

libraries/botbuilder-core/botbuilder/core/activity_handler.py, libraries/botbuilder-core/botbuilder/core/bot_framework_adapter.py, libraries/botbuilder-core/botbuilder/core/bot_state.py, libraries/botbuilder-core/botbuilder/core/conversation_state.py, libraries/botbuilder-dialogs/botbuilder/dialogs/prompts/oauth_prompt.py, libraries/botbuilder-dialogs/botbuilder/dialogs/prompts/prompt.py
Fixing ref docs issues from preview site:
=> mm-api-ref-docs-fixes-wip

libraries/botbuilder-dialogs/botbuilder/dialogs/component_dialog.py, libraries/botbuilder-dialogs/botbuilder/dialogs/dialog_reason.py, libraries/botbuilder-dialogs/botbuilder/dialogs/dialog_state.py, libraries/botbuilder-dialogs/botbuilder/dialogs/dialog_turn_result.py, libraries/botbuilder-dialogs/botbuilder/dialogs/prompts/activity_prompt.py
- Changed notes to remarks
- Fixed method and class names
-
=> emolsh-api-ref-docs-r2

libraries/botbuilder-dialogs/botbuilder/dialogs/choices/choice_recognizers.py, libraries/botbuilder-dialogs/botbuilder/dialogs/choices/find_choices_options.py, libraries/botbuilder-dialogs/tests/test_choice_prompt.py
=> Add FindChoiceOptions for recognize_numbers and recognize_ordinals

libraries/botbuilder-core/botbuilder/core/bot_framework_adapter.py, libraries/botbuilder-core/botbuilder/core/bot_state.py
=> mm-api-ref-docs-build-fixes

libraries/botbuilder-dialogs/botbuilder/dialogs/component_dialog.py, libraries/botbuilder-dialogs/botbuilder/dialogs/dialog_turn_result.py
changes from @emgrol and @mmiele
=> API ref doc fixes round 3

libraries/botbuilder-core/botbuilder/core/re_escape.py, libraries/botbuilder-core/botbuilder/core/turn_context.py, libraries/botbuilder-core/tests/test_turn_context.py
Fixes #743 
The 3.6 re.escape() doesn't work the same as in 3.7. and 3.8, which was causing remove_mention_text to fail.
Copied the 3.8 re.escape() function into botbuilder.
Also, the remove_mention_text assertions weren't correct.  They would never raise a failure.
=> 3.6 tests failing due to remove_mention_text

.github/ISSUE_TEMPLATE/workflows/main.yml
Adds an auto tagging GH action that will tag issues opened by the [PORT] tool that Tom is running
- Adds issue autotagging (similar to JS repo)
=> chore: add issue autotagging

ci-pr-pipeline.yml, libraries/botbuilder-integration-applicationinsights-aiohttp/botbuilder/integration/applicationinsights/aiohttp/about.py
Added botbuilder-adapters-slack to libraries.  Set version on botbuilder-integration-applicationinsights-aiohttp.  Now testing against Python 3.8.2 (from 3.8.1)
=> ci-pr-pipeline changes

libraries/botbuilder-core/botbuilder/core/bot_framework_adapter.py, libraries/botbuilder-core/botbuilder/core/bot_framework_http_client.py, libraries/botbuilder-core/botbuilder/core/turn_context.py, libraries/botbuilder-core/tests/test_bot_framework_adapter.py, libraries/botbuilder-schema/botbuilder/schema/__init__.py, libraries/botbuilder-schema/botbuilder/schema/_connector_client_enums.py, libraries/botbuilder-schema/botbuilder/schema/_models.py, libraries/botbuilder-schema/botbuilder/schema/_models_py3.py, libraries/swagger/ConnectorAPI.json, samples/experimental/skills-buffered/parent/bots/parent_bot.py
Fies: https://github.com/microsoft/botbuilder-python/issues/842
=> Change DeliveryMode bufferedReplies to expectReplies

libraries/botbuilder-schema/botbuilder/schema/teams/_models.py, libraries/botbuilder-schema/botbuilder/schema/teams/_models_py3.py
fixes #836 
Add member_count and channel_count to TeamDetails.
=> add member_count and channel_count to TeamDetails

libraries/botbuilder-core/botbuilder/core/teams/teams_info.py
this might be better as:
```python
client = turn_context.turn_state[BotAdapter.BOT_CONNECTOR_CLIENT_KEY]
```
?
=> Fix teams connector client creation credential retrieval bug

libraries/botbuilder-adapters-slack/botbuilder/adapters/slack/slack_adapter.py
=> continue_conversation in custom adapter

libraries/botbuilder-schema/botbuilder/schema/_connector_client_enums.py, libraries/botbuilder-schema/botbuilder/schema/_models.py, libraries/botbuilder-schema/botbuilder/schema/_models_py3.py
Fixes: https://github.com/microsoft/botbuilder-python/issues/835
=> Add ephemeral to DeliveryModes (parity)

libraries/botbuilder-dialogs/botbuilder/dialogs/dialog_extensions.py, libraries/botbuilder-integration-aiohttp/botbuilder/integration/aiohttp/bot_framework_http_client.py
=> Skills: Cancel dialogs only if EOC is coming from parent.

libraries/botbuilder-core/botbuilder/core/bot_framework_adapter.py, libraries/botbuilder-core/tests/test_bot_framework_adapter.py
C# was using the property name "tenantId" for the Teams channel data.  Python was using "id".
=> Teams tenantId correction

libraries/botbuilder-dialogs/botbuilder/dialogs/prompts/oauth_prompt.py
Fixes #897
Fix mismatched interface and method names in error messages
=>  Fix interface and method names in the OAuth Prompt error messages

libraries/botbuilder-core/botbuilder/core/teams/teams_activity_handler.py, libraries/botbuilder-core/tests/teams/test_teams_activity_handler.py
Fixes #1065 
* Do not call TeamsInfo.get_member for the bot
* fix botid for test
=> Do NOT call TeamsInfo.get_member for the bot: cherry pick 4.9 fix (#1066)

libraries/botbuilder-dialogs/botbuilder/dialogs/prompts/choice_prompt.py, libraries/botbuilder-dialogs/botbuilder/dialogs/prompts/confirm_prompt.py, libraries/botbuilder-dialogs/botbuilder/dialogs/prompts/datetime_prompt.py, libraries/botbuilder-dialogs/botbuilder/dialogs/prompts/number_prompt.py
See parent PR: https://github.com/microsoft/botbuilder-js/pull/2246
Some of the prompts break if user uploads an attachment instead of responding with text because of some of the `string` methods that get called on `activity.text` (which doesn't exist if an attachment is sent).
Add some variation of
```python
if not utterance:
return result
```
to:
1. ChoicePrompt
2. DatetimePrompt
3. NumberPrompt
4. ConfirmPrompt
I also renamed `message` to `utterance` to be more in line with other prompts.
The original issue was only for DatetimePrompt, but I added the other two. Other prompts didn't seem relevant for this.
=> Hardened prompts

libraries/functional-tests/functionaltestbot/requirements.txt, libraries/functional-tests/functionaltestbot/setup.py
No idea whether this is the correct fix for the problem. However, it makes the build run without error.
The failing build: https://fuselabs.visualstudio.com/SDK_v4/_build/results?buildId=128418&view=results
The successful build: https://fuselabs.visualstudio.com/SDK_v4/_build/results?buildId=132248&view=results
=> Possible fix for BotBuilder-Python-Functional-Tests-Linux-yaml build error

libraries/botbuilder-adapters-slack/requirements.txt, libraries/botbuilder-adapters-slack/setup.py, libraries/botbuilder-ai/requirements.txt, libraries/botbuilder-ai/setup.py, libraries/botbuilder-applicationinsights/requirements.txt, libraries/botbuilder-applicationinsights/setup.py, libraries/botbuilder-azure/setup.py, libraries/botbuilder-core/requirements.txt, libraries/botbuilder-core/setup.py, libraries/botbuilder-dialogs/requirements.txt, libraries/botbuilder-dialogs/setup.py, libraries/botbuilder-integration-aiohttp/requirements.txt, libraries/botbuilder-integration-aiohttp/setup.py, libraries/botbuilder-integration-applicationinsights-aiohttp/setup.py, libraries/botbuilder-testing/requirements.txt, libraries/botbuilder-testing/setup.py, libraries/botframework-connector/requirements.txt, libraries/botframework-connector/setup.py
Fixes #1070 
This should allow the latest CookieCutter to work with us (since it depends on requests 2.23.0)
=> Updated requests to 2.23.0, pinned more dependencies

libraries/botbuilder-core/tests/teams/test_teams_channel_data.py, libraries/botbuilder-schema/botbuilder/schema/teams/_models.py, libraries/botbuilder-schema/botbuilder/schema/teams/_models_py3.py
=> Add aadGroupId to TeamInfo

UsingTestPyPI.md, libraries/botbuilder-core/botbuilder/core/teams/teams_activity_handler.py, libraries/botbuilder-core/tests/teams/test_teams_activity_handler.py
on_teams_members_removed is not consistent with the JS and C#. This is a breaking change. I'm not sure how we want to handle this.
=> Adding TeamsInfo to on_teams_member_removed

libraries/botbuilder-adapters-slack/botbuilder/adapters/slack/slack_client.py, libraries/botbuilder-adapters-slack/botbuilder/adapters/slack/slack_helper.py, libraries/botbuilder-adapters-slack/botbuilder/adapters/slack/slack_payload.py, libraries/botbuilder-adapters-slack/setup.py
Added package depencies from requirements.txt to setup.py
=> Adding dependencies to setup.py

libraries/botbuilder-testing/botbuilder/testing/storage_base_tests.py
Related to: https://github.com/microsoft/botbuilder-dotnet/issues/4038
[This commit](https://github.com/microsoft/botbuilder-python/blame/master/libraries/botbuilder-testing/botbuilder/testing/storage_base_tests.py#L134) caused the live tests for Cosmos and Blob to fail because of how e_tags are used in each storage adapter. It wasn't caught because in CI, those tests are disabled (working on the fix in the issue linked above).
The real "issue" here is that this commit, some of the tests had to be commented out in Python, making them differ from the other SDKs. This would generally indicate that therefore, the Python storage adapters behave differently than the other SDKs.
@axelsrz and I discussed this and this is mostly due to a limitation in Python; unlike C# and JS, Python can't have a …
=> Add e_tag to storeItems tests

libraries/botbuilder-schema/botbuilder/schema/_models_py3.py, libraries/botbuilder-schema/tests/test_activity.py
Fixes #1157
Implements the methods from ActivityEx from DotNet in the Activity class. It also adds tests for the Activity class.
Added the Activity methods present in [ActivityEx from BotBuilder-DotNet](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Schema/ActivityEx.cs) to the `_models_py3.py` file.
Created the `test_activity.py` file and Added 55 tests for the methods in the Activity class.
=> Add ActivityEx implementation

libraries/botbuilder-core/botbuilder/core/bot_state.py, libraries/botbuilder-core/tests/test_bot_state.py
Fixes #989
> Port from microsoft/botbuilder-dotnet# 3727
This PR port the fix for bot state so that the context service key is used consistently to access the cached state.
Ported the changes in the PR microsoft/botbuilder-dotnet# 3727.
- Implemented the changes in the class `bot_state.py` to use `BotAssert` and created the method `get_cached_state`.
- Added the test for the `get_cached_state` in the `test_bot_state` class.
Note: the classes `BotStateMemoryScope` and `MemoryScopeTests` are not present in Python to be ported.
Below you can see the tests for the `bot_state` class running.
=> [PORT] Fix bot state so that the context service key is used consistently to access the cached state

libraries/botbuilder-core/botbuilder/core/telemetry_constants.py, libraries/botbuilder-core/botbuilder/core/telemetry_logger_middleware.py
Fixes #940
Logs attachments on outgoing activities in telemetry, if the LogPersonalInformation flag is set to true.
- Added `ATTACHMENTS_PROPERTY` to `telemetry_constants.py`
- Added validation to log the attachment property in `telemetry_logger_middleware.py`
=> Update telemetry logger to include attachments

libraries/botframework-connector/botframework/connector/auth/government_constants.py
Fixes #1022 
This change does not represent any impact for the framework right now. Given that python apps are not possible to deploy in MS Gov cloud right now, this change would only make a difference if the last statement changes in the future.
=> Potential arlington support for the future

.github/CODEOWNERS
Iterates on https://github.com/microsoft/botbuilder-python/pull/1225 which fixed https://github.com/microsoft/botbuilder-python/issues/1208
Adds appropriate Bot Framework SDK GitHub Teams as code owners
Applies @microsoft/bb-python specific ownership over package-crucial files, such as `setup.py` and `MANIFEST.in`
=> [Engineering] update CODEOWNERS

README.md
=> Updated README to include info about pylint and black

libraries/botbuilder-core/botbuilder/core/teams/teams_info.py, libraries/botbuilder-core/tests/teams/test_teams_info.py
Fixes check to check the argument instead of the turn context
=> correcting none check to check parameter

libraries/botbuilder-core/botbuilder/core/activity_handler.py, libraries/botbuilder-core/tests/test_activity_handler.py
=> Added InstallationUpdate Activity type handling

libraries/botbuilder-schema/botbuilder/schema/__init__.py, libraries/botbuilder-schema/botbuilder/schema/speech_constants.py
=> Add a constant for "empty speak tag"

libraries/botbuilder-azure/setup.py
Fixes #1302 
We're currently on `azure-cosmos` v3.1.2. Not a ton of changes in 3.2.0, but it looks like it will be their last stable version, now that they're working on v4:
Updates the `setup.py` in `libraries\botbuilder-azure` to use `azure-cosmos` v3.2.0.
**test_cosmos_storage.py** with `EMULATOR_RUNNING = True`:
**test_cosmos_partitioned_storage.py** with `EMULATOR_RUNNING = True`:
Note: Both test files have warning, but they're all due to not using a SSL Certificate for Cosmos Emulator. Totally normal.
=> Update azure-cosmos to 3.2.0

libraries/botbuilder-core/botbuilder/core/bot_framework_adapter.py, libraries/botbuilder-core/tests/test_bot_framework_adapter.py
=> Fixes Unauthorized error when calling ContinueConversation

libraries/botbuilder-dialogs/botbuilder/dialogs/skills/skill_dialog.py, libraries/botbuilder-dialogs/tests/test_skill_dialog.py
=> Refactored SkillDialog to call ConversationFacotry.CreateConversationId only once

libraries/botbuilder-ai/botbuilder/ai/qna/models/prompt.py, libraries/botbuilder-ai/botbuilder/ai/qna/models/qna_response_context.py, libraries/botbuilder-ai/botbuilder/ai/qna/models/query_result.py, libraries/botbuilder-ai/botbuilder/ai/qna/models/query_results.py, libraries/botbuilder-ai/botbuilder/ai/qna/utils/generate_answer_utils.py, libraries/botbuilder-ai/botbuilder/ai/qna/utils/http_request_utils.py, libraries/botbuilder-ai/tests/qna/test_qna.py
Fixes #1187 
Properly allow requests to be made and consumed using  Python's built-in `requests` library.
This will allow the option to use an HTTP client that isn't from `aiohttp`, which may be a sought out option for frameworks that don't wrap their requests in a running "`ProactorEventLoop`" that's necessary for `aiohttp.ClientSession`'s to work.
For example, using the Quart 13.core-bot sample, it can properly call `QnAMaker` service with just the following
*app.py*
```python
import requests
QNAMAKER = QnAMaker(
endpoint=QnAMakerEndpoint(
knowledge_base_id=APP.config["QNA_KNOWLEDGEBASE_ID"],
endpoint_key=APP.config["QNA_ENDPOINT_KEY"],
host=APP.config["QNA_ENDPOINT_HOST"],
),
http_client=requests
)
```
- Configures the request to `QnAMaker` to the proper shape for the given HTTP …
=> Allow requests module as QnAMaker's HTTP client

libraries/botbuilder-ai/tests/qna/test_qna.py, libraries/botframework-connector/botframework/connector/auth/jwt_token_validation.py, pipelines/botbuilder-python-ci.yml
pinned right version of black in the pipeline
=> Black version updated in pipeline

libraries/botbuilder-adapters-slack/botbuilder/adapters/slack/slack_adapter.py, libraries/botbuilder-adapters-slack/botbuilder/adapters/slack/slack_helper.py, libraries/botbuilder-adapters-slack/botbuilder/adapters/slack/slack_options.py, libraries/botbuilder-ai/botbuilder/ai/luis/luis_recognizer.py, libraries/botbuilder-ai/botbuilder/ai/qna/qnamaker.py, libraries/botbuilder-applicationinsights/botbuilder/applicationinsights/application_insights_telemetry_client.py, libraries/botbuilder-applicationinsights/botbuilder/applicationinsights/django/bot_telemetry_middleware.py, libraries/botbuilder-applicationinsights/botbuilder/applicationinsights/django/logging.py, libraries/botbuilder-integration-aiohttp/botbuilder/integration/aiohttp/bot_framework_http_client.py, libraries/botbuilder-integration-applicationinsights-aiohttp/botbuilder/integration/applicationinsights/aiohttp/aiohttp_telemetry_middleware.py
Fixes for malformed reference comments.
- fixing incorrect RST and Markdown formatting 
- copy editing grammar, tone, and spelling
=> Reference comment fixes

libraries/botbuilder-integration-aiohttp/botbuilder/integration/aiohttp/skills/skill_http_client.py, libraries/botbuilder-integration-aiohttp/requirements.txt, libraries/botbuilder-integration-aiohttp/tests/skills/test_skill_http_client.py
=> Testing SkillHttpClient

libraries/botbuilder-core/botbuilder/core/adapters/test_adapter.py, libraries/botbuilder-core/botbuilder/core/show_typing_middleware.py, libraries/botbuilder-core/tests/test_show_typing_middleware.py
=> Avoid typing activity if is skill

libraries/botbuilder-dialogs/botbuilder/dialogs/dialog_extensions.py, libraries/botbuilder-dialogs/tests/test_dialogextensions.py
=> Add EndOfConversationCodes to EndOfConversation activity from Skill

libraries/botbuilder-core/botbuilder/core/activity_handler.py, libraries/botbuilder-core/tests/test_activity_handler.py
Fixes https://github.com/microsoft/botbuilder-python/issues/1347
While adding this, I realized on_installation_update should be named on_installation_update_activity... yet, we have released it as on_installation_update in 4.10.0 (although this is not likely to be used by any bots just yet, since the event is not sent from Teams yet).  Any recommendation, should we update this event name to match the convention, or leave it?
=> Add installation update sub events to ActivityHandler

libraries/adaptive-expressions/adaptive/expressions/builtin_functions/get_next_viable_time.py, libraries/adaptive-expressions/adaptive/expressions/builtin_functions/get_previous_viable_time.py, libraries/adaptive-expressions/adaptive/expressions/convert_format.py, libraries/adaptive-expressions/tests/test_expression_parser.py
Now `formatDateTime('2018-02-15T12:12:12', \'dd/MM/yyy\')` will return `02/15/2018`
=> fix formatDateTime function with "dd/MM/yyy" produces wrong results

libraries/botbuilder-core/botbuilder/core/channel_service_handler.py, libraries/botbuilder-core/tests/test_channel_service_handler.py, libraries/botbuilder-integration-aiohttp/botbuilder/integration/aiohttp/bot_framework_http_client.py, libraries/botbuilder-integration-aiohttp/tests/test_bot_framework_http_client.py, libraries/botbuilder-schema/botbuilder/schema/_connector_client_enums.py, libraries/botbuilder-schema/botbuilder/schema/_models_py3.py, libraries/botframework-connector/botframework/connector/auth/app_credentials.py, libraries/botframework-connector/botframework/connector/auth/authentication_constants.py, libraries/botframework-connector/botframework/connector/auth/claims_identity.py, libraries/botframework-connector/botframework/connector/auth/jwt_token_validation.py, libraries/botframework-connector/botframework/connector/auth/skill_validation.py, libraries/botframework-connector/tests/test_app_credentials.py, libraries/botframework-connector/tests/test_auth.py, libraries/botframework-connector/tests/test_skill_validation.py, libraries/swagger/ConnectorAPI.json
Fixes #1396
- Added new Skill constant to RoleTypes
- Updated BotframeworkHttpCllient to set the Role in the Recipient of the outgoing activity clone to RoleTypes.Skill
- Updated ChannelServiceHanlder to add an anonymous skill AppId claim when auth is disabled.
- Updated AppCredentials.ShouldSetToken() logic to avoid sending a token when the AppId is not set or when it is set to the anonymous skill appId.
- Updated SkillValidation.IsSkillClaim to return true for anonymous skills.
- Updated JwtTokenValidation.AuthenticateRequest to check the Role property in the incoming activity to determine if the request is coming from another bot or the channel. 
- Added AuthenticationConstants.AnonymousSkillAppId constant.
- Added AuthenticationConstants.AnonymousAuthType constant and updated related …
=> Allow skills with no appId or password

libraries/botbuilder-core/botbuilder/core/__init__.py, libraries/botbuilder-core/botbuilder/core/adapters/test_adapter.py, libraries/botbuilder-core/botbuilder/core/bot_framework_adapter.py, libraries/botbuilder-core/botbuilder/core/conversation_reference_extension.py, libraries/botbuilder-core/botbuilder/core/memory_transcript_store.py, libraries/botbuilder-core/botbuilder/core/transcript_logger.py, libraries/botbuilder-core/tests/test_transcript_logger_middleware.py, libraries/botbuilder-schema/botbuilder/schema/__init__.py, libraries/botbuilder-schema/botbuilder/schema/_models_py3.py
=> TranscriptLogger should not log continue conversation

libraries/botbuilder-schema/botbuilder/schema/teams/__init__.py, libraries/botbuilder-schema/botbuilder/schema/teams/_models_py3.py
=> Teams CacheInfo

libraries/botbuilder-core/botbuilder/core/teams/teams_activity_handler.py
Fixes #1405 
`on_teams_team_renamed_activity()` was mistakenly named against the pattern of the rest of the activity handlers (which don't end in "activity"`
- Add overload method called `on_teams_team_renamed()`
- Add deprecation notice for `on_teams_team_renamed_activity()`
=> Add on_teams_team_renamed "overload"

pipelines/botbuilder-python-ci.yml
This stops the task "Push test results to coveralls" from running and failing for forked PRs. In the case of forks, the task is not allowed access to the coveralls push token for security reasons, making it fail.
A build example: https://fuselabs.visualstudio.com/SDK_v4/_build/results?buildId=177434&view=results
=> Add conditional on push to coveralls to avoid forks errors

libraries/botbuilder-applicationinsights/tests/test_telemetry_waterfall.py, libraries/botbuilder-dialogs/botbuilder/dialogs/waterfall_dialog.py
Fixes #670 
In `WaterfallDialog.get_step_name` method, it uses `__qualname__` dunder method to get a unique name for the waterfall step
```python
def get_step_name(self, index: int) -> str:
"""
Give the waterfall step a unique name
"""
step_name = self._steps[index].__qualname__
if not step_name or ">" in step_name:
step_name = f"Step{index + 1}of{len(self._steps)}"
return step_name
```
The method's intention is to only create and assign a name if the waterfall step is anonymous, which commonplace in C# and JS SDKs. 
However, because the full qualname is given, "`>`" is present, even if waterfall steps defined with a name (i.e. no anonymous methods used to define steps). This results in an overapplication of renaming waterfall step names, even if the step already has a name to begin with. …
=> Only reassign waterfall step name only if the step doesn't have a name

libraries/botbuilder-dialogs/botbuilder/dialogs/dialog_context.py, libraries/botbuilder-dialogs/tests/test_activity_prompt.py
Fixes #1218
Change `DialogContext` to capture exceptions and resolve information about context in each Exception error.
This change is PORTED from DotNet.
Add `try/catch` handlers to `DialogContext` class methods to set `Exception.data["DialogContext']` with metadata about the context.
> **Note:** The PORT does not include the state property in data, because in DotNet it gets it from the `State` property but in Python does not exist.
In the following images there is a sneak peek about the information structure and the passing tests.
=> [#1218] [PORT] Emit better error messages for all dialogs

libraries/botbuilder-core/botbuilder/core/activity_handler.py, libraries/botbuilder-core/tests/test_activity_handler.py
=> Adding add-upgrade and remove-upgrade activity types in ActivityHandler

libraries/botbuilder-adapters-slack/botbuilder/adapters/slack/slack_client.py, libraries/botbuilder-adapters-slack/botbuilder/adapters/slack/slack_event.py, libraries/botbuilder-adapters-slack/botbuilder/adapters/slack/slack_payload.py, libraries/botbuilder-adapters-slack/botbuilder/adapters/slack/slack_request_body.py, libraries/botbuilder-ai/botbuilder/ai/qna/utils/qna_card_builder.py, libraries/botbuilder-schema/botbuilder/schema/health_results.py
=> pylance warnings corrections for List arguments

libraries/botbuilder-dialogs/botbuilder/dialogs/dialog_manager.py, libraries/botbuilder-dialogs/tests/test_dialog_manager.py
Also added checks in the test fo ensure we get the code back
Fixes #1502
=> Updated dialog_manager to send EoC code like dialog_extensions.

libraries/botbuilder-dialogs/botbuilder/dialogs/dialog_container.py, libraries/botbuilder-dialogs/botbuilder/dialogs/dialog_set.py, libraries/botbuilder-dialogs/tests/test_dialog_set.py
=> DialogContainer.telemetryclient

libraries/botbuilder-dialogs/botbuilder/dialogs/dialog_extensions.py, libraries/botbuilder-dialogs/botbuilder/dialogs/dialog_manager.py, libraries/botbuilder-dialogs/botbuilder/dialogs/skills/skill_dialog.py, libraries/botbuilder-dialogs/tests/test_dialog_manager.py
=> Reduce trace activity in dialogs

libraries/botbuilder-ai/botbuilder/ai/qna/utils/qna_card_builder.py, libraries/botbuilder-ai/tests/qna/test_data/QnAMakerDialog_ActiveLearning.json, libraries/botbuilder-ai/tests/qna/test_data/QnAMakerDialog_MultiTurn_Answer1.json, libraries/botbuilder-ai/tests/qna/test_data/QnAMakerDialog_MultiTurn_Answer2.json, libraries/botbuilder-ai/tests/qna/test_qna_dialog.py
Fixes #1571 
Currently when using the multi-turn feature in QnAMakerDialog, it will show "None of the above" 
*Multi-turn prompt has a 3rd extra button, "None of the above"* (Incorrect behavior)
"None of the above" is the "NO MATCH" response for active learning when QnAMaker wants explicit feedback about which of the closely scored answers the user considers is the actual answer their question correctly (in "NO MATCH" case, it means that none of the suggestions that are offered answers the user's question)
This "NO MATCH" response is only supposed to show up in an active learning prompt, however it is incorrectly also showing up fo rmulti-turn as well. See below
1. Ensure that multi-turn prompt **does not** have NO MATCH response present
- …
=> Only show "NO MATCH" response button if active learning is active

libraries/botbuilder-dialogs/botbuilder/dialogs/prompts/__init__.py, libraries/botbuilder-dialogs/botbuilder/dialogs/prompts/choice_prompt.py, libraries/botbuilder-dialogs/botbuilder/dialogs/prompts/confirm_prompt.py, libraries/botbuilder-dialogs/botbuilder/dialogs/prompts/prompt_culture_models.py, libraries/botbuilder-dialogs/tests/test_choice_prompt.py, libraries/botbuilder-dialogs/tests/test_confirm_prompt.py
Fixes #582 
This mainly adjusts Confirm and Choice prompts use of locale to:
1. Use English as default
2. Go away from hard-coding the cultures in each prompt to a single source of truth for supported cultures
3. Accept variations of locale strings ("EN", "en-US", "en-us", etc) (this was an issue in other SDKs for some channels)
4. Add tests for locales
5. Also adds support for Italian, Korean, and Turkish, to match published `recognizers-text` support.
This PR gets these prompts in line with .NET/JS.
=> Add PromptCultureModels, rework prompt locales

libraries/botbuilder-core/botbuilder/core/bot_framework_adapter.py, libraries/botbuilder-core/tests/test_bot_framework_adapter.py
Fixes #1631
This PR fixes the issue found when exchanging a token from the Host to the Skill. The response status is **412** and the body's description `The bot is unable to exchange token. Proceed with regular login.` 
The fix evaluates the correct `exchange_async` method response and returns the actual `TokenResponse` instance.
There is also a fix for the InvokeResponse result in the `process_activity` method, which now will be returning the body serialized.
Also, two new unit tests were included to address these fixes.
- **bot_framework_adapter.py**
- Imported `TokenResponse` from `botframework.connector.token_api.models` as `ConnectorTokenResponse` named class due to existing `TokenResponse` from `bot.builder.schema`.
- Replaced `invoke_response.value` in …
=> [#1631][BotFrameworkAdapter] process_activity returns HTTP 412 error when exchanging a token

libraries/botbuilder-core/botbuilder/core/bot_framework_adapter.py, libraries/botbuilder-core/botbuilder/core/memory_storage.py, libraries/botbuilder-core/botbuilder/core/teams/__init__.py, libraries/botbuilder-core/botbuilder/core/teams/teams_sso_token_exchange_middleware.py
=> SSO Token Exchange Middleware

libraries/botbuilder-streaming/botbuilder/streaming/payload_transport/payload_receiver.py, libraries/botbuilder-streaming/botbuilder/streaming/payload_transport/send_queue.py, libraries/botbuilder-streaming/tests/test_payload_receiver.py
#release (to get pr check passing)
=> payload receiver unit test

libraries/botbuilder-streaming/tests/test_payload_processor.py
Request Processor Test
#release
=> Request Processor Test

libraries/botframework-connector/botframework/connector/auth/skill_validation.py, libraries/botframework-connector/tests/test_auth.py
Fixes #1683
This PR fixes the order of the validations in the [is_skill_claim](https://github.com/microsoft/botbuilder-python/blob/main/libraries/botframework-connector/botframework/connector/auth/skill_validation.py#L62) method to allow using anonymous authentication.
- Updated `skill_validation` class to invert the order of the conditions that validate the VERSION_CLAIM and the ANONYMOUS_SKILL_APP_ID to keep consistency with [.NET](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Connector/Authentication/SkillValidation.cs#L87) and [JS](https://github.com/microsoft/botbuilder-js/blob/main/libraries/botframework-connector/src/auth/skillValidation.ts#L89) SDKs.
- Fixed bug in list initialization in `test_auth`.
This image shows a bot with anonymous …
=> [#1683] Fix is_skill_claim validation for anonymous authentication

libraries/botframework-streaming/tests/test_header_serializer.py, libraries/botframework-streaming/tests/test_payload_assembler.py, libraries/botframework-streaming/tests/test_request_manager.py, libraries/botframework-streaming/tests/test_stream_manager.py
Fixes #1705 
- Header Serializer tests
- Payload Assembler tests
- Request Manager tests
- Stream Manager tests
=> C# parity tests for payloads

libraries/botbuilder-core/botbuilder/core/activity_handler.py, libraries/botbuilder-schema/botbuilder/schema/__init__.py, libraries/botbuilder-schema/botbuilder/schema/_models_py3.py, libraries/botbuilder-schema/botbuilder/schema/teams/_models_py3.py
Fixes #1497 
Adds handler for `adaptiveCard/action` invoke activity.
Note: I'm out of practice with Python, so feel free to nitpick.
=> feat: add adaptive card invoke action handler

libraries/botbuilder-core/botbuilder/core/skills/skill_handler.py
#minor
This PR adds a validation in `skill_handler.py` for the `get_skill_conversation_reference` method.
This missing validation was causing an error in bots with a custom `SkillConversationIdFactory` class, building the reference in the `get_conversation_reference` method, and being over nested.
This issue was introduced in PR #1691, for ISSUE #1687.
With the change in this PR, the users can still use their previous implementation of the `SkillConversationIdFactory`.
The bots used to test are the [WaterfallHostBot Python](https://github.com/microsoft/BotFramework-FunctionalTests/tree/main/Bots/Python/Consumers/CodeFirst/WaterfallHostBot) and [WaterfallSkillBot Python](https://github.com/microsoft/BotFramework-FunctionalTests/tree/main/Bots/Python/Skills/CodeFirst/WaterfallSkillBot) from …
=> Fix get_skill_conversation_reference in skill_handler

libraries/botbuilder-core/botbuilder/core/teams/teams_activity_handler.py, libraries/botbuilder-core/tests/teams/test_teams_activity_handler.py, libraries/botbuilder-schema/botbuilder/schema/teams/__init__.py, libraries/botbuilder-schema/botbuilder/schema/teams/_models_py3.py
Fixes #1690
Adds support to TeamsActivityHandler for meeting start/end events.
Bots implementing this must add this to their `manifest.json`:
```json
"webApplicationInfo": {
"id": "<MicrosoftAppId>",
"resource": "<urlToApp>",
"applicationPermissions": [
"OnlineMeeting.ReadBasic.Chat"
]
}
```
Note that somebody needs to actually start/join the meeting for this to work. The scheduled start/end times mean nothing for this event.
=> support teams meeting start/end events

libraries/botbuilder-dialogs/botbuilder/dialogs/dialog_extensions.py, libraries/botbuilder-dialogs/botbuilder/dialogs/dialog_manager.py
=> DialogManager logic moved to DialogExtensions

README.md, libraries/botbuilder-core/requirements.txt, libraries/botbuilder-core/setup.py, libraries/botframework-streaming/setup.py
=> Added depending on streaming to botbuilder-core

libraries/botbuilder-core/botbuilder/core/bot_framework_adapter.py
=> Fixed issue with channel_data being overwritten in create_conversation

libraries/botbuilder-dialogs/botbuilder/dialogs/dialog_context.py
Fixes #1685 
See JS https://github.com/microsoft/botbuilder-js/blob/d57152ab47e0b02cef23f629775ba9f77d930b0f/libraries/botbuilder-dialogs/src/dialogContext.ts#L285
=> Corrected DialogContext.cancel_all_dialogs

libraries/botbuilder-applicationinsights/setup.py
Fixes #1803
Django 1.11 before 1.11.28, 2.2 before 2.2.10, and 3.0 before 3.0.3 allows SQL Injection if untrusted data is used as a StringAgg delimiter (e.g., in Django applications that offer downloads of data as a series of rows with a user-specified column delimiter). By passing a suitably crafted delimiter to a contrib.postgres.aggregates.StringAgg instance, it was possible to break escaping and inject malicious SQL.
https://dev.azure.com/FuseLabs/SDK_v4/_componentGovernance/112465/alert/2370216?typeId=4354877
Fix version spec in setup.py
=> Fix Django Component Governance vulnerability.

generators/LICENSE.md, generators/README.md, generators/app/templates/echo/cookiecutter.json, generators/app/templates/echo/{{cookiecutter.bot_name}}/.pylintrc, generators/app/templates/echo/{{cookiecutter.bot_name}}/README.md, generators/app/templates/echo/{{cookiecutter.bot_name}}/app.py, generators/app/templates/echo/{{cookiecutter.bot_name}}/bot.py, generators/app/templates/echo/{{cookiecutter.bot_name}}/config.py, generators/app/templates/echo/{{cookiecutter.bot_name}}/deploymentTemplates/template-with-new-rg.json, generators/app/templates/echo/{{cookiecutter.bot_name}}/deploymentTemplates/template-with-preexisting-rg.json, generators/app/templates/echo/{{cookiecutter.bot_name}}/requirements.txt
Addresses #1848
#minor
This PR adds the python generators' **Echo bot** from the [BotBuider-Samples](https://github.com/microsoft/BotBuilder-Samples/tree/main/generators/python) repository.
It also includes the root documentation for the generators folder.
- Added LICENSE, and README docs.
- Added `generators/app/templates/echo` folder
These images show the echo bot being generated and working.
=> [#1848] Move python generators from Samples to "generators" - Echo bot

generators/app/templates/empty/cookiecutter.json, generators/app/templates/empty/{{cookiecutter.bot_name}}/.pylintrc, generators/app/templates/empty/{{cookiecutter.bot_name}}/README.md, generators/app/templates/empty/{{cookiecutter.bot_name}}/app.py, generators/app/templates/empty/{{cookiecutter.bot_name}}/bot.py, generators/app/templates/empty/{{cookiecutter.bot_name}}/config.py, generators/app/templates/empty/{{cookiecutter.bot_name}}/deploymentTemplates/template-with-new-rg.json, generators/app/templates/empty/{{cookiecutter.bot_name}}/deploymentTemplates/template-with-preexisting-rg.json, generators/app/templates/empty/{{cookiecutter.bot_name}}/requirements.txt
Addresses #1848
#minor
This PR adds the python generators' **Empty bot** from the [BotBuider-Samples](https://github.com/microsoft/BotBuilder-Samples/tree/main/generators/python) repository.
- Added `generators/app/templates/empty` folder
These images show the empty bot being generated and working.
=> [#1848] Move python generators from Samples to "generators" - Empty bot

libraries/functional-tests/functionaltestbot/Dockerfile
Fixes #minor
The warning: 
##[warning]Container security analysis found 1 violations. This repo has one or more docker files having references to images from external registries.
Example: [BotBuilder-Python-CI-PR-yaml](https://dev.azure.com/FuseLabs/SDK_v4/_build/results?buildId=305837&view=logs&j=7533eaef-a325-552b-21cf-5b0ebc256c06&t=aed58e65-c6f4-5601-4415-570d60f85914)
Change the FROM in libraries/functional-tests/functionaltestbot/Dockerfile to reference the appropriate container image in the Microsoft Artifact Registry.
=> fix: DockerFile security analysis warning - Python

libraries/botbuilder-core/botbuilder/core/cloud_adapter_base.py
Fixes #2036
Minor fix to latest changes on cloudAdapter.(create|continue)_conversation
=> fix: cloudAdapter.update_conversation() add app_id parameter

libraries/botbuilder-core/botbuilder/core/cloud_adapter_base.py, libraries/botbuilder-core/tests/simple_adapter.py, libraries/botbuilder-core/tests/teams/simple_adapter_with_create_conversation.py
Fixes #2040 
fix usage of `ResourceResponse` to use named parameter `id`
=> #2040: fix usage of ResourceResponse to use named argument

libraries/botbuilder-core/botbuilder/core/teams/teams_info.py, libraries/botbuilder-core/tests/teams/test_teams_activity_handler.py, libraries/botbuilder-integration-aiohttp/botbuilder/integration/aiohttp/cloud_adapter.py
=> Ensure Connector Client is retrieved in teams_info.py

README.md, libraries/botbuilder-adapters-slack/requirements.txt, libraries/botbuilder-ai/setup.py, libraries/botbuilder-integration-aiohttp/requirements.txt, libraries/botbuilder-integration-aiohttp/setup.py, libraries/botbuilder-integration-applicationinsights-aiohttp/setup.py, libraries/botframework-connector/tests/requirements.txt, pipelines/botbuilder-python-ci.yml
=> aiohttp to 3.9.3

libraries/botbuilder-adapters-slack/tests/test_slack_client.py
=> Skipping Slack test if env not setup

libraries/botbuilder-schema/botbuilder/schema/teams/_models_py3.py
Fixes #2084 
Fixes `TeamsChannelAccount.add_object_id` property.
The curent definition returns an additional property and a null `add_object_id`:
```python
{'additional_property': {'aadObjectId': <UUID>}, 'add_object_id`: None}
```
instead of:
```python
{'additional_properties': {}, `add_object_id` <UUID>}
```
See: https://learn.microsoft.com/en-us/dotnet/api/microsoft.bot.schema.teams.teamschannelaccount?view=botbuilder-dotnet-stable
=> Fix TeamsChannelAccount model

libraries/botframework-connector/botframework/connector/auth/authentication_constants.py, libraries/botframework-connector/botframework/connector/auth/government_constants.py, libraries/botframework-connector/botframework/connector/auth/microsoft_app_credentials.py
=> OAuthScope parity with JS and DotNet

README.md
=> Updated README with supported Python versions

libraries/botbuilder-dialogs/botbuilder/dialogs/prompts/oauth_prompt.py
=> Removed invalid exchange_token check

libraries/botbuilder-core/botbuilder/core/channel_service_handler.py, libraries/botbuilder-integration-aiohttp/botbuilder/integration/aiohttp/cloud_adapter.py, libraries/botbuilder-integration-aiohttp/botbuilder/integration/aiohttp/configuration_service_client_credential_factory.py, libraries/botframework-connector/botframework/connector/auth/__init__.py, libraries/botframework-connector/botframework/connector/auth/_parameterized_bot_framework_authentication.py, libraries/botframework-connector/botframework/connector/auth/jwt_token_validation.py, libraries/botframework-connector/botframework/connector/auth/managedidentity_app_credentials.py, libraries/botframework-connector/botframework/connector/auth/managedidentity_service_client_credential_factory.py, libraries/botframework-connector/requirements.txt, libraries/botframework-connector/setup.py
=> UserAssigned MSI support

libraries/botbuilder-ai/botbuilder/ai/qna/models/join_operator.py, libraries/botbuilder-ai/botbuilder/ai/qna/models/qna_response_context.py, libraries/botbuilder-ai/botbuilder/ai/qna/models/qnamaker_trace_info.py, libraries/botbuilder-ai/botbuilder/ai/qna/models/query_results.py, libraries/botbuilder-ai/botbuilder/ai/qna/qnamaker_options.py, libraries/botbuilder-ai/botbuilder/ai/qna/utils/active_learning_utils.py, libraries/botbuilder-ai/botbuilder/ai/qna/utils/generate_answer_utils.py, libraries/botbuilder-ai/botbuilder/ai/qna/utils/http_request_utils.py, libraries/botbuilder-ai/botbuilder/ai/qna/utils/train_utils.py, libraries/botbuilder-dialogs/botbuilder/dialogs/choices/choice_factory.py, libraries/botbuilder-dialogs/botbuilder/dialogs/choices/choice_recognizers.py, libraries/botbuilder-dialogs/botbuilder/dialogs/choices/find_choices_options.py, libraries/botbuilder-dialogs/botbuilder/dialogs/choices/find_values_options.py, libraries/botbuilder-dialogs/botbuilder/dialogs/choices/found_choice.py, libraries/botbuilder-dialogs/botbuilder/dialogs/choices/found_value.py, libraries/botbuilder-dialogs/botbuilder/dialogs/choices/model_result.py, libraries/botbuilder-dialogs/botbuilder/dialogs/choices/sorted_value.py, libraries/botbuilder-dialogs/botbuilder/dialogs/choices/token.py, libraries/botbuilder-dialogs/botbuilder/dialogs/choices/tokenizer.py
Fixes #1991 
To avoid generating unwanted H1 headers in API reference documents, remove the colon (':') from keywords such as "Parameters", "Remarks" and "Returns" in comments.
See the proper usage in: https://www.sphinx-doc.org/en/master/usage/extensions/example_numpy.html
=> Remove the colon (':') from keywords such as "Parameters", "Remarks" and "Returns" in comments.

libraries/botframework-connector/botframework/connector/auth/__init__.py, libraries/botframework-connector/botframework/connector/auth/certificate_app_credentials.py, libraries/botframework-connector/botframework/connector/auth/certificate_government_app_credentials.py, libraries/botframework-connector/botframework/connector/auth/certificate_service_client_credential_factory.py, libraries/botframework-connector/tests/test_certificate_service_client_credential_factory.py
=> Added CertificateServiceClientCredentialsFactory

libraries/botframework-connector/botframework/connector/auth/microsoft_app_credentials.py
Fixes #2139 
The `auth_token` object may not contain an access token due to auth failing. Raise an exception with helpful error message instead.
=> Raise PermissionError if access_token not available on auth_token object

libraries/botbuilder-core/botbuilder/core/teams/teams_activity_handler.py, libraries/botbuilder-core/tests/teams/test_teams_activity_handler.py, libraries/botbuilder-schema/botbuilder/schema/teams/__init__.py, libraries/botbuilder-schema/botbuilder/schema/teams/_models_py3.py, libraries/botframework-connector/botframework/connector/auth/microsoft_app_credentials.py
Fixes #minor
Porting [[Teams] Add support for meeting participants added/removed events (#6677)](https://github.com/microsoft/botbuilder-dotnet/pull/6677) to maintain parity with `microsoft/botbuilder-dotnet`
- Added support for 2 new activity types - `application/vnd.microsoft.meetingParticipantJoin` and `application/vnd.microsoft.meetingParticipantLeave`.
- Added functions to register handlers for when teams meeting participants are joined/left.
- Added unit test
=> Port: [Teams] Add support for meeting participants added/removed events

libraries/botbuilder-integration-aiohttp/botbuilder/integration/aiohttp/bot_framework_http_client.py, libraries/botframework-connector/botframework/connector/aio/operations_async/_conversations_operations_async.py, libraries/botframework-connector/botframework/connector/operations/_conversations_operations.py
Fixes #1754
Porting [Add conversation id header in skill requests #5741](https://github.com/microsoft/botbuilder-dotnet/pull/5741) to maintain parity with `microsoft/botbuilder-dotnet`
- Adding conversation id header in skill requests
=> [Port]: Add conversation id header in skill requests

libraries/botbuilder-core/botbuilder/core/adapters/test_adapter.py, libraries/botbuilder-schema/botbuilder/schema/_models_py3.py
Fixes #1695
Porting [Fix first activity from bot to user has fake replyToId value (#5313)](https://github.com/microsoft/botbuilder-dotnet/pull/5313) to maintain parity with `microsoft/botbuilder-dotnet`
When the activity is the first one of the conversation and it's sent from bot to user, the ReplyToId was assigned to the bogus ConversationUpdate activity's id. The fix is to not assign the bogus ReplyToId if previous activity is the ConversationUpdate activity
- Do not assign ReplyToId if conversantionReference is from ConversationUpdate activity
Note: The test cases included in the porting PR are not added here, as they have been reverted to maintain 100% code coverage for Microsoft.Bot.Schema.
=> port: Fix first activity from bot to user has fake replyToId value

libraries/botframework-connector/tests/requirements.txt
Fixes #2150
Error installing PyYAML==6.0 with Python 3.12 and 3.13 from
`pip install -r ./libraries/botframework-connector/tests/requirements.txt`
Bump PyYAML 6.0 to 6.0.1 
Successfully installed
`pip install -r ./libraries/botframework-connector/tests/requirements.txt`
=> Bump PyYAML 6.0 to 6.0.1

libraries/botbuilder-ai/botbuilder/ai/qna/qnamaker.py, libraries/botbuilder-ai/setup.py, libraries/botbuilder-applicationinsights/botbuilder/applicationinsights/flask/flask_telemetry_middleware.py, libraries/botbuilder-dialogs/botbuilder/dialogs/choices/choice_factory.py, libraries/botbuilder-dialogs/botbuilder/dialogs/dialog.py, libraries/botbuilder-integration-aiohttp/botbuilder/integration/aiohttp/streaming/aiohttp_web_socket.py, libraries/botbuilder-integration-aiohttp/setup.py, libraries/botbuilder-integration-applicationinsights-aiohttp/setup.py, libraries/botbuilder-schema/botbuilder/schema/_models_py3.py
#minor
Updates aiohttp from 3.9.5 to 3.10.2
- [libraries/botbuilder-ai/setup.py](https://github.com/microsoft/botbuilder-python/blob/main/libraries/botbuilder-ai/setup.py)
- [libraries/botbuilder-integration-aiohttp/setup.py](https://github.com/microsoft/botbuilder-python/blob/main/libraries/botbuilder-integration-aiohttp/setup.py)
- [libraries/botbuilder-integration-applicationinsights-aiohttp/setup.py](https://github.com/microsoft/botbuilder-python/blob/main/libraries/botbuilder-integration-applicationinsights-aiohttp/setup.py)
https://github.com/microsoft/botbuilder-python/pull/2152
=> aiohttp 3.10.2

libraries/botbuilder-core/botbuilder/core/turn_context.py
Previous type hint implied that send_activity in turn_context.py will always return ResourceResponse, meanwhile it can also return None
Fixes #2146
The type hint is fixed to include possible None return, otherwise it might make the developers assume that there is no need to check for None.
- Changed ResourceResponse to Union[ResourceResponse, None] type hint
=> Fixed type hint in turn_context.py

libraries/botbuilder-schema/setup.py
Fixes #2142 
Remove the upper version bound constraint added in #2051. It’s unclear why it was added as @tracyboehrer left no notes. See [this mega blog post](https://iscinumpy.dev/post/bound-version-constraints/) for a long explanier on why libraries should avoid such constraints.
Per title
Relying on CI.
=> Remove urllib3 upper bound version constraint

libraries/botbuilder-core/botbuilder/core/teams/teams_activity_handler.py, libraries/botbuilder-core/tests/teams/test_teams_activity_handler.py, libraries/botbuilder-schema/botbuilder/schema/teams/__init__.py, libraries/botbuilder-schema/botbuilder/schema/teams/_models_py3.py, libraries/botbuilder-schema/tests/teams/test_bot_config_auth.py, libraries/botbuilder-schema/tests/teams/test_config_auth_response.py, libraries/botbuilder-schema/tests/teams/test_config_response.py, libraries/botbuilder-schema/tests/teams/test_config_task_response.py
Fixes #minor
This PR ports the changes in https://github.com/microsoft/botbuilder-dotnet/pull/6632. Add new Teams invoke types 'config/fetch' and 'config/submit' for supporting Auth & TaskModuleContinue in configuration flow.
- Add support for new config invoke requests `'config/fetch'` and `'config/submit' `
- For config, add `ConfigAuthResponse`, `ConfigResponse`, and `BotConfigAuthType `for parsing config payloads.
These images show the new unit tests passing.
=> Port: Add support for new Teams invoke types 'config/fetch' and 'config/submit'

libraries/botbuilder-core/botbuilder/core/teams/__init__.py, libraries/botbuilder-core/botbuilder/core/teams/teams_activity_extensions.py, libraries/botbuilder-core/tests/teams/test_teams_extension.py, libraries/botbuilder-schema/botbuilder/schema/teams/__init__.py, libraries/botbuilder-schema/botbuilder/schema/teams/_models_py3.py
Fixes #minor
This PR ports the changes from https://github.com/microsoft/botbuilder-dotnet/pull/6360. It adds the ability to gather the selected MS Team's channel id when available in the incoming Activity.
- Added the `teams_get_selected_channel_id `helper function.
-  Added the `TeamsChannelDataSettings ` model and all its related properties to be accessible from the Activity.
- Added unit tests around this implementation.
- Updated `__init__.py` to include the new added properties.
Below image shows the new unit tests passing.
=> Port: Add settings.selectedChannel to TeamsChannelData and Type to ChannelInfo and TeamDetails

libraries/botbuilder-core/botbuilder/core/teams/teams_activity_extensions.py, libraries/botbuilder-core/tests/teams/test_teams_channel_data.py, libraries/botbuilder-core/tests/teams/test_teams_extension.py, libraries/botbuilder-schema/botbuilder/schema/teams/__init__.py, libraries/botbuilder-schema/botbuilder/schema/teams/_models_py3.py
Fixes #minor
This PR ports the changes from https://github.com/microsoft/botbuilder-dotnet/pull/6609 
- Adds the OnBehalfOf property to send messages via bots on behalf of another user in Teams.
- It also adds unit tests to cover the new code.
- Added the `OnBehalfOf `property in the `TeamsChannelData `class.
- Added the `teams_get_team_on_behalf_of `method to return the current activity's _OnBehalfOf_ list.
The following image shows the related unit test passing.
=> Port: TeamsChannelData need OnBehalfOf [#6609]

libraries/botbuilder-dialogs/botbuilder/dialogs/skills/skill_dialog.py
Fixes #minor
This PR ports the changes from https://github.com/microsoft/botbuilder-dotnet/pull/6848 to maintain parity with `microsoft/botbuilder-dotnet`.
This PR updates the `_intercept_oauth_cards` method in `SkillDialog` to support `CloudAdapter` in combination with expect replies delivery mode.
- In `_intercept_oauth_cards` added a call to `_UserTokenAccess.exchange_token` method, which handles both adapters.
The following image shows the related unit test passing.
=> port: SkillDialog.InterceptOAuthCardsAsync doesn't support CloudAdapter (#6848)

libraries/botbuilder-dialogs/botbuilder/dialogs/_user_token_access.py
Fixes #2176
Add missing parameter: `connection_name` in `exchange_token()` call.
- Added missing parameter: `connection_name` in `exchange_token()` call under [_user_token_access.py](https://github.com/microsoft/botbuilder-python/blob/main/libraries/botbuilder-dialogs/botbuilder/dialogs/_user_token_access.py) to enable proper token exchange flow.
=> Add missing parameter in exchange_token() call

libraries/botbuilder-core/botbuilder/core/activity_handler.py, libraries/botbuilder-core/botbuilder/core/teams/teams_activity_handler.py, libraries/botbuilder-core/tests/teams/test_teams_activity_handler.py, libraries/botbuilder-core/tests/test_activity_handler.py
Fixes #minor
This PR ports the changes from https://github.com/microsoft/botbuilder-dotnet/pull/6564 to maintain parity with `microsoft/botbuilder-dotnet`.
This PR aims to extend the Bot SDK so that developers can consume newly added events that Teams will emit to the bot. They are:
`TeamsMessageEdit `- a user editing a message in Teams.
`TeamsMessageUndelete `- a user undo a deleted message in Teams.
`TeamsMessageSoftDelete `- a user soft deleting a message in Teams.
1. Extended `ActivityHandler` to handle `MessageUpdate `and `MessageDelete` activity types and dispatch functions for activity types.
2. Extended `TeamsActivityHandler `to handle `MessageUpdate `(with subtypes `TeamsMessageEdit `and `TeamsMessageUndelete`) and `MessageDelete `(with subtype `TeamsMessageSoftDelete`) teams …
=> Port: Support Teams message edit, message soft delete, message undelete activities

libraries/botbuilder-core/botbuilder/core/teams/teams_activity_handler.py, libraries/botbuilder-core/tests/teams/test_teams_activity_handler.py
Fixes #minor
This PR port the changes from https://github.com/microsoft/botbuilder-dotnet/pull/6524
This PR adds a new invoke handler for the invoke name `composeExtension/anonymousQueryLink`.
This invoke will get triggered when an user pastes a link for an app that has opted in to the zero install link unfurling feature. The interface is identical to existing handler for composeExtension/queryLink, but the user sensitive information will be anonymized for anonymousQueryLink.
- Added new invoke handler for composeExtension/anonymousQueryLink
The following image shows the related unit test passing.
=> Port: Add new handler for anonymous query link invoke

libraries/botbuilder-core/botbuilder/core/teams/teams_activity_extensions.py, libraries/botbuilder-core/tests/teams/test_teams_extension.py
Fixes #223 
Porting changes from https://github.com/microsoft/botbuilder-dotnet/pull/6136
The logic for `teams_notify_user` helper method is incorrect. It should set either alertInMeeting to true, or alert to true, but not both.
https://github.com/microsoft/botbuilder-python/blob/3e76e543477500b7e56f53ba20258b730ec4f924/libraries/botbuilder-core/botbuilder/core/teams/teams_activity_extensions.py#L74-L75
- Set TeamsNotifyUser alert to opposite of alert_in_meeting
The following image shows the related unit test passing.
=> Port: Set TeamsNotifyUser alert to opposite of alert_in_meeting

generators/app/templates/core/{{cookiecutter.bot_name}}/deploymentTemplates/deployUseExistResourceGroup/parameters-for-template-AzureBot-with-rg.json, generators/app/templates/core/{{cookiecutter.bot_name}}/deploymentTemplates/deployUseExistResourceGroup/parameters-for-template-BotApp-with-rg.json, generators/app/templates/core/{{cookiecutter.bot_name}}/deploymentTemplates/deployUseExistResourceGroup/readme.md, generators/app/templates/core/{{cookiecutter.bot_name}}/deploymentTemplates/deployUseExistResourceGroup/template-AzureBot-with-rg.json, generators/app/templates/core/{{cookiecutter.bot_name}}/deploymentTemplates/deployUseExistResourceGroup/template-BotApp-with-rg.json, generators/app/templates/core/{{cookiecutter.bot_name}}/deploymentTemplates/deployWithNewResourceGroup/parameters-for-template-AzureBot-new-rg.json, generators/app/templates/core/{{cookiecutter.bot_name}}/deploymentTemplates/deployWithNewResourceGroup/parameters-for-template-BotApp-new-rg.json, generators/app/templates/core/{{cookiecutter.bot_name}}/deploymentTemplates/deployWithNewResourceGroup/readme.md, generators/app/templates/core/{{cookiecutter.bot_name}}/deploymentTemplates/deployWithNewResourceGroup/template-AzureBot-new-rg.json, generators/app/templates/core/{{cookiecutter.bot_name}}/deploymentTemplates/deployWithNewResourceGroup/template-BotApp-new-rg.json, generators/app/templates/echo/{{cookiecutter.bot_name}}/deploymentTemplates/deployUseExistResourceGroup/parameters-for-template-AzureBot-with-rg.json, generators/app/templates/echo/{{cookiecutter.bot_name}}/deploymentTemplates/deployUseExistResourceGroup/parameters-for-template-BotApp-with-rg.json, generators/app/templates/echo/{{cookiecutter.bot_name}}/deploymentTemplates/deployUseExistResourceGroup/readme.md, generators/app/templates/echo/{{cookiecutter.bot_name}}/deploymentTemplates/deployUseExistResourceGroup/template-AzureBot-with-rg.json, generators/app/templates/echo/{{cookiecutter.bot_name}}/deploymentTemplates/deployUseExistResourceGroup/template-BotApp-with-rg.json, generators/app/templates/echo/{{cookiecutter.bot_name}}/deploymentTemplates/deployWithNewResourceGroup/parameters-for-template-AzureBot-new-rg.json, generators/app/templates/echo/{{cookiecutter.bot_name}}/deploymentTemplates/deployWithNewResourceGroup/parameters-for-template-BotApp-new-rg.json, generators/app/templates/echo/{{cookiecutter.bot_name}}/deploymentTemplates/deployWithNewResourceGroup/readme.md, generators/app/templates/echo/{{cookiecutter.bot_name}}/deploymentTemplates/deployWithNewResourceGroup/template-AzureBot-new-rg.json, generators/app/templates/echo/{{cookiecutter.bot_name}}/deploymentTemplates/deployWithNewResourceGroup/template-BotApp-new-rg.json, generators/app/templates/empty/{{cookiecutter.bot_name}}/deploymentTemplates/deployUseExistResourceGroup/parameters-for-template-AzureBot-with-rg.json, generators/app/templates/empty/{{cookiecutter.bot_name}}/deploymentTemplates/deployUseExistResourceGroup/parameters-for-template-BotApp-with-rg.json, generators/app/templates/empty/{{cookiecutter.bot_name}}/deploymentTemplates/deployUseExistResourceGroup/readme.md, generators/app/templates/empty/{{cookiecutter.bot_name}}/deploymentTemplates/deployUseExistResourceGroup/template-AzureBot-with-rg.json, generators/app/templates/empty/{{cookiecutter.bot_name}}/deploymentTemplates/deployUseExistResourceGroup/template-BotApp-with-rg.json, generators/app/templates/empty/{{cookiecutter.bot_name}}/deploymentTemplates/deployWithNewResourceGroup/parameters-for-template-AzureBot-new-rg.json, generators/app/templates/empty/{{cookiecutter.bot_name}}/deploymentTemplates/deployWithNewResourceGroup/parameters-for-template-BotApp-new-rg.json, generators/app/templates/empty/{{cookiecutter.bot_name}}/deploymentTemplates/deployWithNewResourceGroup/readme.md, generators/app/templates/empty/{{cookiecutter.bot_name}}/deploymentTemplates/deployWithNewResourceGroup/template-AzureBot-new-rg.json, generators/app/templates/empty/{{cookiecutter.bot_name}}/deploymentTemplates/deployWithNewResourceGroup/template-BotApp-new-rg.json
Fixes #2187
Added missing parameters: `appType`, `UMSIName`, `UMSIResourceGroupName`, and `tenantId` to the ARM template for Python bot deployment.
- Added missing parameters: `appType`, `UMSIName`, `UMSIResourceGroupName`, and `tenantId` in `parameters-for-template-AzureBot-with-rg.json`
- Updated `readme.md`
=> Added missing parameters to the ARM template for Python bot deployment.

libraries/botbuilder-core/tests/teams/test_teams_activity_handler.py, libraries/botbuilder-dialogs/tests/choices/test_choice_recognizers.py, libraries/botbuilder-testing/setup.py, libraries/botframework-connector/tests/requirements.txt
Fixes #2168
[botbuilder.testing] Relax dependency to allow pytest 8
- Updated `pytest `version to `8.3.3`
- Updated `pytest-asyncio` version to `0.24.0`
- Updated `pytest-cov` version to `>=5.0.0`
- Fixed `ModuleNotFoundError: No module named 'simple_adapter'` in `test_teams_activity_handler.py`
- Fixed `PytestAssertRewriteWarning: assertion is always true, perhaps remove parentheses?` in `test_choice_recognizers.py`
Ran the `pip install commands` and `pytest` in the following Python versions, and they are working as expected
`Python 3.13.0, 3.12.5, 3.11.9, 3.10.11, 3.9.13, 3.8.10`
=> Bumped pytest

libraries/botframework-connector/botframework/connector/auth/certificate_app_credentials.py
…
Fixes the same issue as reported in #2105, but for certificate app credentials.
Generate and log a proper error message on auth errors, instead of just `exception: KeyError('access_token')`
=> Port auth error handling from microsoft_app_credentials to certificate_app_credentials

libraries/botbuilder-core/botbuilder/core/turn_context.py, libraries/botbuilder-core/tests/test_turn_context.py
Fixes #2210 
This pull request includes changes to the `remove_mention_text` method in `turn_context.py` and adds a new test case in `test_turn_context.py` to ensure the method works correctly with custom mentions.
Improvements to `remove_mention_text` method:
* [`libraries/botbuilder-core/botbuilder/core/turn_context.py`](diffhunk://#diff-e80e0302ba9095fcef94e0004e727e78057cffb08bce12ef4339f05ed6d43e5cR399-R405): Modified the `remove_mention_text` method to handle cases where the mention text is not directly available by using either the `text` or `name` property from `additional_properties`.
Additions to test cases:
* [`libraries/botbuilder-core/tests/test_turn_context.py`](diffhunk://#diff-0aebc3cd5165e7e1ee742045c212d5a38e59a19a6fe57e9726e0d5964f01d530R353-R394): Added a new test case …
=> MentionRemoved fix

libraries/botbuilder-dialogs/botbuilder/dialogs/dialog.py
Fixes #2214
The function name is emit_event, not emit
- Modified the name
I would need guidance on what test to modify that currently has emit_event in the codebase.
=> fix: Method name is emit_event, not emit

README.md
contributing goes to a 404 — file not found, https://github.com/microsoft/botbuilder-python/blob/main/contributing.md
The correct link is https://github.com/microsoft/botbuilder-python/blob/main/Contributing.md
=> Typo on link
