microsoft/botbuilder-python

samples/Echo.Connector.Bot.Adapter/README.md
samples/Echo.Connector.Bot/README.md

"R" was capitalized... Lame PR, I know.

Update README.md to fix capitalization

---

libraries/botbuilder-core/botbuilder/core/bot_adapter.py
libraries/botbuilder-core/botbuilder/core/bot_context.py
libraries/botbuilder-core/botbuilder/core/bot_framework_adapter.py

add gdpr methods, acceptingInput hint

---

README.md

Added Preview tag, remove experimental

Update read.me for Preview release

---

libraries/botbuilder-core/botbuilder/core/about.py
libraries/botbuilder-core/requirements.txt
libraries/botbuilder-core/setup.py
libraries/botframework-connector/botframework/connector/auth/microsoft_app_credentials.py
libraries/botframework-connector/setup.py
libraries/botframework-connector/tests/test_auth.py
samples/Echo.Connector.Bot.Adapter/requirements.txt

Also bumps version numbers for botframework-connector and botbuilder-core to prepare for publish.

Fix auth header/v4 emulator bug and skip test_auth.py

---

libraries/botbuilder-core/botbuilder/core/__init__.py
libraries/botbuilder-core/botbuilder/core/card_factory.py
libraries/botbuilder-core/botbuilder/core/message_factory.py
libraries/botbuilder-core/tests/test_card_factory.py
libraries/botbuilder-core/tests/test_message_factory.py

- Add `CardFactory` and its tests
- Add `MessageFactory` and its tests

add CardFactory, MessageFactory and tests

---

libraries/botbuilder-core/botbuilder/core/bot_framework_adapter.py
libraries/botframework-connector/botframework/connector/auth/channel_validation.py
libraries/botframework-connector/botframework/connector/auth/emulator_validation.py
libraries/botframework-connector/botframework/connector/auth/endorsements_validator.py
libraries/botframework-connector/botframework/connector/auth/jwt_token_extractor.py
libraries/botframework-connector/botframework/connector/auth/jwt_token_validation.py
libraries/botframework-connector/tests/test_auth.py
libraries/botframework-connector/tests/test_endorsements_validator.py
samples/Echo-Connector-Bot/main.py

Based on C# work (https://github.com/Microsoft/botbuilder-dotnet/pull/655)

Port Token Endorsements

---

samples/EchoBot-with-State/README.md
samples/Rich-Cards-Bot/README.md
samples/Rich-Cards-Bot/Rich-Cards-Bot.bot
samples/Rich-Cards-Bot/adaptive_card_example.py
samples/Rich-Cards-Bot/main.py
samples/Rich-Cards-Bot/requirements.txt

- and update README.md for EchoBot-With-State

add simple Rich-Cards-Bot sample

---

samples/Rich-Cards-Bot/README.md

Added python 3.5 or above requirement

---

README.md

update SDK-V3 url

---

README.md
libraries/botbuilder-azure/botbuilder/azure/about.py
libraries/botbuilder-core/README.rst
libraries/botbuilder-core/botbuilder/core/about.py
libraries/botbuilder-schema/README.rst
libraries/botbuilder-schema/setup.py
libraries/botframework-connector/README.rst
libraries/botframework-connector/setup.py

Added variable for changing the version in daily builds. Added the Azure Pipelines badge to readme pages

Added variable for changing the version in daily builds

---

libraries/botbuilder-applicationinsights/tests/test_telemetry_waterfall.py
libraries/botbuilder-core/botbuilder/core/memory_storage.py
libraries/botbuilder-core/tests/test_memory_storage.py

Remove deepcopy to mimic how other MemoryStorage stuff works in other languages.

Remove deepcopy

---

libraries/botbuilder-ai/botbuilder/ai/luis/luis_prediction_options.py
libraries/botbuilder-ai/botbuilder/ai/luis/luis_recognizer.py
libraries/botbuilder-ai/botbuilder/ai/luis/luis_util.py
libraries/botbuilder-ai/botbuilder/ai/luis/recognizer_result.py
libraries/botbuilder-ai/tests/luis/luis_recognizer_test.py
libraries/botbuilder-ai/tests/luis/override_fill_recognizer.py
libraries/botbuilder-ai/tests/luis/telemetry_override_recognizer.py

* serialize for RecognizerResult, LuisResult etc.
* add test for telemetry
* add test for trace activity

serialization: py json interop

---

samples/python-flask/13.core-bot/config.py
samples/python-flask/13.core-bot/dialogs/booking_dialog.py
samples/python-flask/13.core-bot/dialogs/date_resolver_dialog.py
samples/python-flask/13.core-bot/dialogs/main_dialog.py
samples/python-flask/13.core-bot/main.py

- Import/References to Timex library were pulling from the wrong library.  
- Fix comment referring to Echobot.

Fix references to Timex library, comment for sample

---

libraries/botbuilder-core/botbuilder/core/bot_framework_adapter.py
libraries/botframework-connector/botframework/connector/auth/constants.py
libraries/botframework-connector/botframework/connector/auth/microsoft_app_credentials.py
libraries/botframework-connector/tests/test_attachments.py
libraries/botframework-connector/tests/test_attachments_async.py
libraries/botframework-connector/tests/test_auth.py
libraries/botframework-connector/tests/test_conversations.py
libraries/botframework-connector/tests/test_conversations_async.py

Python connector with Channel Token Tenant
*This PR address issue #136

Python connector with Channel Token Tenant

---

libraries/botbuilder-dialogs/botbuilder/dialogs/__init__.py

Prompts exported from both dialogs and dialogs.prompts without collisions
*This PR address issue #166

Prompts exported from botbuilder.dialogs

---

samples/python-flask/13.core-bot/helpers/luis_helper.py
samples/python-flask/13.core-bot/main.py

Three things addressed:
- Configuration using incorrect casing to pull LUIS properties (@tsuwandy found!)
- Luis results weren't being processed correctly.
- Fix task so it runs in the context of existing loop (like Axel's fix with making converting from `requests` to `aiohttp` earlier).

Fix LUIS helper to handle response correctly

---

samples/Core-Bot/config.yaml
samples/Core-Bot/helpers/luis_helper.py

There seems to be a bug in LuisRecognizer for entities but this fix will get the sample working properly for now.

Fixed up  luis_helper in core-bot sample

---

libraries/botbuilder-schema/botbuilder/schema/_connector_client_enums.py
libraries/botbuilder-schema/botbuilder/schema/_models.py
libraries/botbuilder-schema/botbuilder/schema/_models_py3.py
libraries/swagger/ConnectorAPI.json

callerId, SemanticActionStates, and other swagger file updates

---

samples/python-flask/13.core-bot/app.py

Fix to await on the main loop.  This is already fixed in the Application Insights sample.

Fix aux_func to use await.

---

libraries/botbuilder-core/botbuilder/core/adapters/test_adapter.py
libraries/botbuilder-dialogs/botbuilder/dialogs/prompts/activity_prompt.py
libraries/botbuilder-dialogs/botbuilder/dialogs/prompts/prompt.py
libraries/botbuilder-dialogs/botbuilder/dialogs/prompts/prompt_validator_context.py
libraries/botbuilder-dialogs/tests/test_activity_prompt.py

Fixes on prompt, prompt_validator_context, activity_prompt and test_adapter

Tests for activity prompt. 

---

libraries/botbuilder-azure/botbuilder/azure/cosmosdb_storage.py
libraries/botbuilder-azure/tests/test_cosmos_storage.py

Pylint fixes for azure library code and tests

azure pylint issues

---

libraries/botbuilder-applicationinsights/botbuilder/applicationinsights/application_insights_telemetry_client.py
libraries/botbuilder-applicationinsights/botbuilder/applicationinsights/integration_post_data.py
libraries/botbuilder-applicationinsights/tests/test_telemetry_waterfall.py
libraries/botbuilder-core/botbuilder/core/bot_telemetry_client.py
libraries/botbuilder-core/botbuilder/core/null_telemetry_client.py

Pylint fixes for botbuilder-applicationinsights module code and tests (with some changes in core)

pylint fixes for code and tests

---

libraries/botbuilder-core/botbuilder/core/bot_framework_adapter.py
libraries/botbuilder-core/botbuilder/core/bot_telemetry_client.py
libraries/botbuilder-core/botbuilder/core/null_telemetry_client.py
libraries/botframework-connector/botframework/connector/auth/channel_validation.py
libraries/botframework-connector/botframework/connector/auth/jwt_token_extractor.py
libraries/botframework-connector/botframework/connector/auth/jwt_token_validation.py
libraries/botframework-connector/botframework/connector/token_api/operations/_bot_sign_in_operations.py

Merge validation token fix from 4.5 into master

Axsuarez/cherrypick 4.5

---

libraries/botbuilder-core/botbuilder/core/auto_save_state_middleware.py
libraries/botbuilder-core/botbuilder/core/middleware_set.py
libraries/botbuilder-core/botbuilder/core/show_typing_middleware.py
libraries/botbuilder-core/botbuilder/core/telemetry_logger_middleware.py
libraries/botbuilder-core/botbuilder/core/transcript_logger.py
libraries/botbuilder-core/tests/call_counting_middleware.py
libraries/botbuilder-core/tests/test_auto_save_middleware.py
libraries/botbuilder-core/tests/test_middleware_set.py

Changed on_process_request for on_turn in middleware

---

libraries/botbuilder-applicationinsights/setup.py

Add missing flask package

---

samples/13.core-bot/cards/welcomeCard.json
samples/21.corebot-app-insights/bots/resources/welcomeCard.json
samples/experimental/101.corebot-bert-bidaf/bot/bots/resources/welcomeCard.json
samples/python_django/13.core-bot/bots/resources/welcomeCard.json

Same changes as in botbuilder-samples repo.
https://github.com/microsoft/BotBuilder-Samples/pull/1776  to address https://github.com/microsoft/BotBuilder-Samples/issues/1759

welcomecard isSubtle field value update from "yes" to "true"

---

.pylintrc

Updating pylint rules to comply to latest version

Updating pylint rules to comply to latest version

---

libraries/functional-tests/functionaltestbot/template/linux/template.json

Placeholder skeleton ARM template that deploys python bot.

Functional (e2e) test ARM template

---

samples/45.state-management/bots/state_management_bot.py

Fixes #425: Using incorrect BotState

---

libraries/botbuilder-ai/setup.py
libraries/botbuilder-applicationinsights/setup.py
libraries/botbuilder-azure/setup.py
libraries/botbuilder-core/setup.py
libraries/botbuilder-dialogs/setup.py
libraries/botbuilder-schema/setup.py
libraries/botbuilder-testing/setup.py
libraries/botframework-connector/setup.py

* Updated Classifiers tags in setup.py
* Pinned regex version, remove this dependency when fixed in recognizers

Updated Classifiers tags in setup.py (#516)

---

libraries/botbuilder-schema/setup.py

* exporting teams from botbuilder schema
* black:exporting teams from botbuilder schema

exporting teams from botbuilder schema (#520)

---

libraries/botframework-connector/setup.py

(cherry picked from commit e31677d69fe4967f6083cfcf775aff5bd44158dd)

Added botframework.connector.teams.operations to setup.py (#538) -> 4.7

---

libraries/botbuilder-core/botbuilder/core/teams/teams_info.py

Access _credentials from turn_context adapter when creating teams connector client

Teams connector client creation cleanup

---

libraries/botbuilder-core/botbuilder/core/integration/aiohttp_channel_service_exception_middleware.py
libraries/botframework-connector/botframework/connector/auth/channel_validation.py
libraries/botframework-connector/botframework/connector/auth/emulator_validation.py
libraries/botframework-connector/botframework/connector/auth/enterprise_channel_validation.py
libraries/botframework-connector/botframework/connector/auth/government_channel_validation.py
libraries/botframework-connector/botframework/connector/auth/jwt_token_validation.py

This is so we can handle:  https://github.com/microsoft/BotBuilder-Samples/issues/2073

Raising PermissionError for auth failures.

---

libraries/botframework-connector/botframework/connector/auth/microsoft_app_credentials.py

Fixes: https://github.com/microsoft/botbuilder-python/issues/596

Fix expired token issue

---

libraries/botbuilder-core/botbuilder/core/bot_state.py

mm-api-ref-docs-bot-state

---

libraries/botbuilder-dialogs/botbuilder/dialogs/prompts/prompt.py

Added reference documentation.

mm-api-ref-docs-prompt

---

README.md

- remove preview mentions now that Python is GA

docs: remove preview notes

---

libraries/botbuilder-core/botbuilder/core/turn_context.py
libraries/botbuilder-core/tests/test_turn_context.py

Special chars in bot_name cause remove_mention_text to fail

---

libraries/botbuilder-integration-applicationinsights-aiohttp/setup.py

aiohttp appinsights consistent package versions

---

ci-pr-pipeline.yml

Rename coveralls token var to PythonCoverallsToken, the name in the key vault.

Set up to get secrets from key vault

---

libraries/botbuilder-dialogs/botbuilder/dialogs/prompts/oauth_prompt.py

Parity with microsoft/botbuilder-js#1907

set signInLink to empty when OAuthAppCredentials is set

---

libraries/botbuilder-core/botbuilder/core/show_typing_middleware.py
libraries/botbuilder-core/tests/test_show_typing_middleware.py

ShowTypingMiddleware fixes (switch to asyncio.ensure_future & sleep)

---

libraries/botbuilder-dialogs/botbuilder/dialogs/prompts/oauth_prompt.py

Fixed typo causing [bug 190353](https://ceapex.visualstudio.com/Engineering/_workitems/edit/190353).

Ref doc comment fix - bug 190353

---

libraries/botbuilder-schema/botbuilder/schema/teams/_models_py3.py

Fixes #476 
Most of the changes were just doc changes to remove in invalid reference.

TaskModuleContinueResponse and TaskModuleMessageResponse corrections.

---

libraries/botbuilder-core/botbuilder/core/activity_handler.py
libraries/botbuilder-core/tests/teams/test_teams_activity_handler.py
libraries/botbuilder-core/tests/test_activity_handler.py

Added ActivityHandler.on_typing_activity and tests.

---

libraries/botbuilder-dialogs/botbuilder/dialogs/component_dialog.py

Updated comments to [fix errors causing build issues](https://ceapex.visualstudio.com/Onboarding/_workitems/edit/194592?src=WorkItemMention&src-action=artifact_link) with botbuilder-dialogs (use of :var: in reference comments).

Fixed build error in Project 194592

---

libraries/botbuilder-integration-aiohttp/botbuilder/integration/aiohttp/bot_framework_http_client.py

fix for creating response with empty content in bfhttpadapter

---

libraries/botbuilder-ai/README.rst

- Update build badge in all README.rst. 
- Corrected installation command for some lib rst
fixes #608

Updating badges in rst

---

libraries/botbuilder-schema/botbuilder/schema/teams/_models_py3.py

Added AppBasedQuery state property.

---

libraries/botbuilder-integration-aiohttp/botbuilder/integration/aiohttp/bot_framework_http_client.py
libraries/botbuilder-integration-aiohttp/tests/test_bot_framework_http_client.py

Setting default Recipient on BotFrameworkHttpClient.post_activity

---

libraries/botbuilder-integration-aiohttp/botbuilder/integration/aiohttp/bot_framework_http_client.py

Fix'NoneType' object has no attribute 'is_government'

---

libraries/botframework-connector/botframework/connector/auth/jwt_token_extractor.py

See the description in https://github.com/microsoft/botbuilder-python/issues/990

Fix for refreshing open id metadata issue.

---

libraries/botbuilder-core/botbuilder/core/bot_framework_adapter.py
pipelines/botbuilder-python-ci.yml

Using bot oauth scope instead of TurnState value

---

libraries/botbuilder-core/botbuilder/core/skills/skill_handler.py
libraries/botbuilder-core/botbuilder/core/turn_context.py
libraries/botbuilder-core/tests/test_bot_framework_adapter.py
libraries/botbuilder-core/tests/test_turn_context.py
libraries/botbuilder-dialogs/botbuilder/dialogs/dialog_extensions.py
libraries/botbuilder-schema/botbuilder/schema/_models.py
libraries/botbuilder-schema/botbuilder/schema/_models_py3.py

Fixes #988 
* Adds locale for EndOfConversation events and activities
* Adds locale for ConversationReference
Added checks for `locale` in existing tests.

Locale fixes

---

libraries/botbuilder-core/botbuilder/core/teams/teams_activity_handler.py
libraries/botbuilder-core/tests/simple_adapter.py
libraries/botbuilder-core/tests/teams/test_teams_activity_handler.py

Fixes: https://github.com/microsoft/botbuilder-python/issues/974

Change onTeamsMemberAdded for Teams to use getMember()

---

libraries/botbuilder-core/botbuilder/core/__init__.py
libraries/botbuilder-core/botbuilder/core/activity_handler.py
libraries/botbuilder-core/botbuilder/core/healthcheck.py
libraries/botbuilder-core/tests/test_activity_handler.py
libraries/botbuilder-schema/botbuilder/schema/__init__.py
libraries/botbuilder-schema/botbuilder/schema/health_results.py
libraries/botbuilder-schema/botbuilder/schema/healthcheck_response.py

Added HealthCheck

---

libraries/botbuilder-core/botbuilder/core/bot_framework_adapter.py
libraries/botbuilder-core/botbuilder/core/invoke_response.py
libraries/botbuilder-dialogs/botbuilder/dialogs/skills/begin_skill_dialog_options.py
libraries/botbuilder-dialogs/botbuilder/dialogs/skills/skill_dialog.py
libraries/botbuilder-dialogs/botbuilder/dialogs/skills/skill_dialog_options.py
libraries/botbuilder-dialogs/tests/test_skill_dialog.py

SkillDialog activity type handling updates

---

libraries/botbuilder-core/botbuilder/core/teams/teams_activity_handler.py
libraries/botbuilder-core/tests/teams/test_teams_activity_handler.py

Fixes: https://github.com/microsoft/botbuilder-python/issues/1065
(this needs to also be cherry-picked to master)

Do NOT call TeamsInfo.get_member for the bot

---

libraries/botbuilder-dialogs/botbuilder/dialogs/prompts/prompt.py

Related: https://github.com/microsoft/botbuilder-dotnet/pull/4172/commits/caab65dae5516543656a722ab00524d9c350fe7b

Fix doc comment for on_prompt

---

libraries/botbuilder-adapters-slack/botbuilder/adapters/slack/slack_adapter.py
libraries/botbuilder-ai/botbuilder/ai/luis/luis_application.py
libraries/botbuilder-ai/botbuilder/ai/luis/luis_recognizer.py
libraries/botbuilder-ai/botbuilder/ai/qna/qnamaker.py
libraries/botbuilder-applicationinsights/botbuilder/applicationinsights/application_insights_telemetry_client.py
libraries/botbuilder-core/botbuilder/core/bot_adapter.py
libraries/botbuilder-core/botbuilder/core/bot_telemetry_client.py
libraries/botbuilder-core/botbuilder/core/null_telemetry_client.py
libraries/botbuilder-core/botbuilder/core/skills/conversation_id_factory.py
libraries/botbuilder-core/botbuilder/core/skills/skill_handler.py

Updating reference comments to fix formatting issues on SDK site. 
- Removed parentheses from `:func:`
- Fixed parameter lists

R10 reference doc fixes

---

libraries/botbuilder-ai/setup.py

Fixes #1188
This is for the 4.9 branch.

Added missing QnA dialogs export

---

libraries/botbuilder-schema/botbuilder/schema/_models_py3.py

Add CardAction imageAltText

---

libraries/botbuilder-dialogs/botbuilder/dialogs/choices/channel.py

Remove Slack from the list of channels that support Suggested Actions

---

libraries/botbuilder-adapters-slack/botbuilder/adapters/slack/slack_payload.py

Slack adapter updates for dialog interactions

---

libraries/botbuilder-applicationinsights/botbuilder/applicationinsights/application_insights_telemetry_client.py

Added ApplicationInsights Queue size setting

---

.github/CODEOWNERS

Initial CODEOWNERS

---

pipelines/botbuilder-python-ci.yml

Updating python versions to unblock builds

Changed Python versions to always use latest on Azure

---

libraries/botbuilder-core/botbuilder/core/skills/skill_handler.py
libraries/botbuilder-core/tests/skills/test_skill_handler.py

return ResourceResponse

---

libraries/botbuilder-applicationinsights/botbuilder/applicationinsights/processor/telemetry_processor.py

Fixes #673 
This also corrects a bug in property TelemetryProcessor.activity_json where a value was not being returned because the get_request_body could return a dict instead of a string.

Implement hash for App Insights session ID

---

libraries/botbuilder-core/botbuilder/core/telemetry_logger_middleware.py
libraries/botbuilder-core/tests/test_telemetry_middleware.py

Add Teams specific telemetry properties

---

libraries/botbuilder-core/tests/teams/test_teams_info.py

Adding unit tests to TeamsInfo

---

libraries/botbuilder-core/botbuilder/core/bot_framework_adapter.py

Add support for skill OAuthCard to Emulator and WebChat

---

libraries/adaptive-expressions/adaptive/expressions/builtin_functions/add_ordinal.py
libraries/adaptive-expressions/adaptive/expressions/builtin_functions/comparison_evaluator.py
libraries/adaptive-expressions/adaptive/expressions/builtin_functions/count_word.py
libraries/adaptive-expressions/adaptive/expressions/builtin_functions/ends_with.py
libraries/adaptive-expressions/adaptive/expressions/builtin_functions/eol.py
libraries/adaptive-expressions/adaptive/expressions/builtin_functions/index_of.py
libraries/adaptive-expressions/adaptive/expressions/builtin_functions/last_index_of.py
libraries/adaptive-expressions/adaptive/expressions/builtin_functions/new_guid.py
libraries/adaptive-expressions/adaptive/expressions/builtin_functions/sentence_case.py
libraries/adaptive-expressions/adaptive/expressions/builtin_functions/starts_with.py
libraries/adaptive-expressions/adaptive/expressions/builtin_functions/string_transform_evaluator.py
libraries/adaptive-expressions/adaptive/expressions/builtin_functions/sum.py
libraries/adaptive-expressions/adaptive/expressions/builtin_functions/title_case.py
libraries/adaptive-expressions/adaptive/expressions/builtin_functions/to_lower.py
libraries/adaptive-expressions/adaptive/expressions/builtin_functions/to_upper.py
libraries/adaptive-expressions/adaptive/expressions/builtin_functions/trim.py
libraries/adaptive-expressions/adaptive/expressions/expression.py
libraries/adaptive-expressions/adaptive/expressions/expression_functions.py
libraries/adaptive-expressions/adaptive/expressions/expression_type.py
libraries/adaptive-expressions/adaptive/expressions/function_utils.py
libraries/adaptive-expressions/tests/test_expression_parser.py

Add buildin function for adaptive expression.
Still working on it...

Add buildin function

---

libraries/botbuilder-dialogs/botbuilder/dialogs/prompts/activity_prompt.py

Parity with JS: https://github.com/microsoft/botbuilder-js/pull/744
See also: https://github.com/microsoft/botbuilder-dotnet/pull/4263

Make ActivityPrompt a normal class - remove ABC

---

pipelines/botbuilder-python-ci.yml

Using DevOps feature for code coverage

Added coverage report to the pipeline

---

libraries/botbuilder-dialogs/botbuilder/dialogs/prompts/oauth_prompt.py
libraries/botbuilder-dialogs/botbuilder/dialogs/prompts/oauth_prompt_settings.py
libraries/botbuilder-dialogs/tests/test_oauth_prompt.py

Fixes https://github.com/microsoft/botbuilder-python/issues/1320
and 
Fixes https://github.com/microsoft/botbuilder-python/issues/1336

Add end_on_invalid_message and fix timeout issue

---

libraries/botbuilder-ai/botbuilder/ai/luis/luis_recognizer.py

Fixes #
Updated Recognizer to not return intents if there is no utterance
Fix for issue #1159

Fixed Recognizer on empty utterance

---

libraries/botbuilder-core/tests/skills/test_skill_handler.py

Fixes #1248 
The changes to SkillHandler in C# were already present in Python.  The unit test was different though, so this PR is just the unit test changes.

SkillHandler doesn't return ResourceResponse when forwarding activities

---

libraries/botbuilder-core/botbuilder/core/skills/skill_handler.py
libraries/botbuilder-core/tests/skills/test_skill_handler.py

Support update and delete from skills

---

libraries/botframework-connector/botframework/connector/auth/emulator_validation.py
libraries/botframework-connector/botframework/connector/auth/skill_validation.py

Add values to the list of issues in the emulator and skills token validation code.

update token validation issues

---

libraries/botbuilder-core/botbuilder/core/turn_context.py
libraries/botbuilder-dialogs/botbuilder/dialogs/skills/skill_dialog.py

Invoke with expected replies

---

libraries/botbuilder-dialogs/botbuilder/dialogs/choices/channel.py

Port of https://github.com/microsoft/botbuilder-dotnet/pull/5024

[PORT] Update channel.py to make it clear that Telegram supports card actions

---

libraries/botframework-connector/setup.py

Updating msal dependency

---

libraries/botbuilder-ai/setup.py
libraries/botbuilder-ai/tests/requirements.txt
libraries/botbuilder-azure/setup.py
libraries/botbuilder-core/setup.py
libraries/botbuilder-integration-aiohttp/setup.py
libraries/botbuilder-integration-applicationinsights-aiohttp/setup.py
libraries/botframework-connector/requirements.txt
libraries/botframework-connector/setup.py

updating dependencies

---

.github/workflows/pr-style.yml

feat: add pr style linting

---

libraries/botbuilder-testing/setup.py

adding missing requirements in bb-testing

---

libraries/botbuilder-core/botbuilder/core/bot_framework_adapter.py
libraries/botbuilder-core/botbuilder/core/memory_storage.py
libraries/botbuilder-core/botbuilder/core/teams/__init__.py
libraries/botbuilder-core/botbuilder/core/teams/teams_sso_token_exchange_middleware.py

#release
Cherry picking SSO Token Exchange Middleware

SSO Token Exchange Middleware (#1641)

---

libraries/botbuilder-streaming/botbuilder/streaming/payloads/assemblers/payload_stream_assembler.py

UnblockActivityProcessorThread

---

libraries/botbuilder-core/botbuilder/core/teams/teams_activity_handler.py

Changing super() call to self on members added/removed in TeamsActivityHandler
Fixes #1674

Changing super() call to self on members added/removed in TAH

---

libraries/botbuilder-dialogs/botbuilder/dialogs/memory/scopes/turn_memory_scope.py

turn memory scope includesnapshot to false

---

libraries/botframework-streaming/README.rst

Fixing readme rst

---

libraries/botframework-connector/botframework/connector/token_api/_token_api_client.py
libraries/botframework-connector/botframework/connector/token_api/aio/_token_api_client_async.py
libraries/botframework-connector/setup.py

Fixed the exporting of token api module

---

libraries/botframework-streaming/setup.py

exporting streaming assemblers

---

libraries/botbuilder-schema/botbuilder/schema/teams/_models_py3.py

Fixing TeamsChannelData typo

---

libraries/botframework-connector/tests/test_auth.py

Fixes #1801
Deleted from these locations:
libraries\botframework-connector\tests\test_auth.py(115, 142, 168, 208, 234, 259, 280)

Delete app ids, pws.

---

libraries/botbuilder-dialogs/botbuilder/dialogs/prompts/oauth_prompt.py

OAuthPrompt was constructing InvokeResponse incorrectly in some cases.

---

libraries/botbuilder-dialogs/botbuilder/dialogs/prompts/oauth_prompt.py

[4.14.1] OAuthPrompt was constructing InvokeResponse incorrectly in some cases

---

generators/app/templates/core/cookiecutter.json
generators/app/templates/core/{{cookiecutter.bot_name}}/.pylintrc
generators/app/templates/core/{{cookiecutter.bot_name}}/README-LUIS.md
generators/app/templates/core/{{cookiecutter.bot_name}}/README.md
generators/app/templates/core/{{cookiecutter.bot_name}}/__init__.py
generators/app/templates/core/{{cookiecutter.bot_name}}/adapter_with_error_handler.py
generators/app/templates/core/{{cookiecutter.bot_name}}/app.py
generators/app/templates/core/{{cookiecutter.bot_name}}/booking_details.py
generators/app/templates/core/{{cookiecutter.bot_name}}/bots/__init__.py
generators/app/templates/core/{{cookiecutter.bot_name}}/bots/dialog_and_welcome_bot.py
generators/app/templates/core/{{cookiecutter.bot_name}}/bots/dialog_bot.py
generators/app/templates/core/{{cookiecutter.bot_name}}/cards/welcomeCard.json
generators/app/templates/core/{{cookiecutter.bot_name}}/cognitiveModels/FlightBooking.json
generators/app/templates/core/{{cookiecutter.bot_name}}/config.py
generators/app/templates/core/{{cookiecutter.bot_name}}/deploymentTemplates/template-with-new-rg.json
generators/app/templates/core/{{cookiecutter.bot_name}}/deploymentTemplates/template-with-preexisting-rg.json
generators/app/templates/core/{{cookiecutter.bot_name}}/dialogs/__init__.py
generators/app/templates/core/{{cookiecutter.bot_name}}/dialogs/booking_dialog.py
generators/app/templates/core/{{cookiecutter.bot_name}}/dialogs/cancel_and_help_dialog.py
generators/app/templates/core/{{cookiecutter.bot_name}}/dialogs/date_resolver_dialog.py
generators/app/templates/core/{{cookiecutter.bot_name}}/dialogs/main_dialog.py
generators/app/templates/core/{{cookiecutter.bot_name}}/flight_booking_recognizer.py
generators/app/templates/core/{{cookiecutter.bot_name}}/helpers/__init__.py
generators/app/templates/core/{{cookiecutter.bot_name}}/helpers/dialog_helper.py
generators/app/templates/core/{{cookiecutter.bot_name}}/helpers/luis_helper.py
generators/app/templates/core/{{cookiecutter.bot_name}}/requirements.txt

Addresses #1848
#minor
This PR adds the python generators' **Core bot** from the [BotBuider-Samples](https://github.com/microsoft/BotBuilder-Samples/tree/main/generators/python) repository.
- Added `generators/app/templates/core` folder
These images show the core bot being generated and working.

[#1848] Move python generators from Samples to "generators" - Core bot

---

libraries/botbuilder-core/botbuilder/core/serializer_helper.py
libraries/botbuilder-core/tests/teams/test_teams_activity_handler.py

Fixing bug if channel sends empty string for a null object

---

libraries/botbuilder-ai/requirements.txt
libraries/botbuilder-applicationinsights/requirements.txt
libraries/botbuilder-core/requirements.txt
libraries/botbuilder-dialogs/requirements.txt
libraries/botbuilder-integration-aiohttp/requirements.txt
libraries/botbuilder-schema/requirements.txt
libraries/botbuilder-schema/setup.py
libraries/botframework-connector/requirements.txt
libraries/botframework-connector/setup.py
libraries/botframework-streaming/requirements.txt

Patch update on msrest dependency

---

libraries/botbuilder-ai/requirements.txt
libraries/botbuilder-applicationinsights/requirements.txt
libraries/botbuilder-core/requirements.txt
libraries/botbuilder-dialogs/requirements.txt
libraries/botbuilder-integration-aiohttp/requirements.txt
libraries/botbuilder-schema/requirements.txt
libraries/botbuilder-schema/setup.py
libraries/botframework-connector/requirements.txt
libraries/botframework-connector/setup.py
libraries/botframework-streaming/requirements.txt

Merging msrest update and fixing conflicts

---

libraries/botbuilder-core/botbuilder/core/telemetry_logger_middleware.py
libraries/botbuilder-core/tests/test_telemetry_middleware.py
libraries/botbuilder-dialogs/setup.py

Corrected TeamsChannelData deserialization in TelemetryLoggerMiddleware

---

libraries/botbuilder-applicationinsights/setup.py
libraries/botframework-connector/tests/requirements.txt

Dependency updates

---

generators/app/templates/core/{{cookiecutter.bot_name}}/requirements.txt
generators/app/templates/echo/{{cookiecutter.bot_name}}/requirements.txt
generators/app/templates/empty/{{cookiecutter.bot_name}}/requirements.txt

Bumped generator dependencies

---

generators/app/templates/core/{{cookiecutter.bot_name}}/deploymentTemplates/deployUseExistResourceGroup/parameters-for-template-AzureBot-with-rg.json
generators/app/templates/core/{{cookiecutter.bot_name}}/deploymentTemplates/deployUseExistResourceGroup/parameters-for-template-BotApp-with-rg.json
generators/app/templates/core/{{cookiecutter.bot_name}}/deploymentTemplates/deployUseExistResourceGroup/readme.md
generators/app/templates/core/{{cookiecutter.bot_name}}/deploymentTemplates/deployUseExistResourceGroup/template-AzureBot-with-rg.json
generators/app/templates/core/{{cookiecutter.bot_name}}/deploymentTemplates/deployUseExistResourceGroup/template-BotApp-with-rg.json
generators/app/templates/core/{{cookiecutter.bot_name}}/deploymentTemplates/deployWithNewResourceGroup/parameters-for-template-AzureBot-new-rg.json
generators/app/templates/core/{{cookiecutter.bot_name}}/deploymentTemplates/deployWithNewResourceGroup/parameters-for-template-BotApp-new-rg.json
generators/app/templates/core/{{cookiecutter.bot_name}}/deploymentTemplates/deployWithNewResourceGroup/readme.md
generators/app/templates/core/{{cookiecutter.bot_name}}/deploymentTemplates/deployWithNewResourceGroup/template-AzureBot-new-rg.json
generators/app/templates/core/{{cookiecutter.bot_name}}/deploymentTemplates/deployWithNewResourceGroup/template-BotApp-new-rg.json
generators/app/templates/echo/{{cookiecutter.bot_name}}/deploymentTemplates/deployUseExistResourceGroup/parameters-for-template-AzureBot-with-rg.json
generators/app/templates/echo/{{cookiecutter.bot_name}}/deploymentTemplates/deployUseExistResourceGroup/parameters-for-template-BotApp-with-rg.json
generators/app/templates/echo/{{cookiecutter.bot_name}}/deploymentTemplates/deployUseExistResourceGroup/readme.md
generators/app/templates/echo/{{cookiecutter.bot_name}}/deploymentTemplates/deployUseExistResourceGroup/template-AzureBot-with-rg.json
generators/app/templates/echo/{{cookiecutter.bot_name}}/deploymentTemplates/deployUseExistResourceGroup/template-BotApp-with-rg.json
generators/app/templates/echo/{{cookiecutter.bot_name}}/deploymentTemplates/deployWithNewResourceGroup/parameters-for-template-AzureBot-new-rg.json
generators/app/templates/echo/{{cookiecutter.bot_name}}/deploymentTemplates/deployWithNewResourceGroup/parameters-for-template-BotApp-new-rg.json
generators/app/templates/echo/{{cookiecutter.bot_name}}/deploymentTemplates/deployWithNewResourceGroup/readme.md
generators/app/templates/echo/{{cookiecutter.bot_name}}/deploymentTemplates/deployWithNewResourceGroup/template-AzureBot-new-rg.json
generators/app/templates/echo/{{cookiecutter.bot_name}}/deploymentTemplates/deployWithNewResourceGroup/template-BotApp-new-rg.json
generators/app/templates/empty/{{cookiecutter.bot_name}}/deploymentTemplates/deployUseExistResourceGroup/parameters-for-template-AzureBot-with-rg.json
generators/app/templates/empty/{{cookiecutter.bot_name}}/deploymentTemplates/deployUseExistResourceGroup/parameters-for-template-BotApp-with-rg.json
generators/app/templates/empty/{{cookiecutter.bot_name}}/deploymentTemplates/deployUseExistResourceGroup/readme.md
generators/app/templates/empty/{{cookiecutter.bot_name}}/deploymentTemplates/deployUseExistResourceGroup/template-AzureBot-with-rg.json
generators/app/templates/empty/{{cookiecutter.bot_name}}/deploymentTemplates/deployUseExistResourceGroup/template-BotApp-with-rg.json
generators/app/templates/empty/{{cookiecutter.bot_name}}/deploymentTemplates/deployWithNewResourceGroup/parameters-for-template-AzureBot-new-rg.json
generators/app/templates/empty/{{cookiecutter.bot_name}}/deploymentTemplates/deployWithNewResourceGroup/parameters-for-template-BotApp-new-rg.json
generators/app/templates/empty/{{cookiecutter.bot_name}}/deploymentTemplates/deployWithNewResourceGroup/readme.md
generators/app/templates/empty/{{cookiecutter.bot_name}}/deploymentTemplates/deployWithNewResourceGroup/template-AzureBot-new-rg.json
generators/app/templates/empty/{{cookiecutter.bot_name}}/deploymentTemplates/deployWithNewResourceGroup/template-BotApp-new-rg.json

Correct template folder casing (2)

---

libraries/botbuilder-ai/requirements.txt
libraries/botbuilder-applicationinsights/requirements.txt
libraries/botbuilder-core/requirements.txt
libraries/botbuilder-dialogs/requirements.txt
libraries/botbuilder-integration-aiohttp/requirements.txt
libraries/botbuilder-schema/requirements.txt
libraries/botbuilder-schema/setup.py
libraries/botframework-connector/requirements.txt
libraries/botframework-connector/setup.py
libraries/botframework-streaming/requirements.txt

Updating masal and msrest dependencies

---

libraries/botbuilder-core/requirements.txt
libraries/botbuilder-dialogs/requirements.txt
libraries/botframework-connector/botframework/connector/auth/emulator_validation.py
libraries/botframework-connector/botframework/connector/auth/jwt_token_extractor.py
libraries/botframework-connector/botframework/connector/auth/skill_validation.py
libraries/botframework-connector/requirements.txt
libraries/botframework-connector/setup.py

PyJWT udpated by sdawodu

---

libraries/botbuilder-applicationinsights/setup.py

Updated django

---

libraries/botframework-streaming/setup.py

Corrected streaming dependencies

---

libraries/botbuilder-ai/requirements.txt
libraries/botbuilder-ai/setup.py
libraries/botbuilder-applicationinsights/setup.py
libraries/botbuilder-testing/setup.py

Bumped pytest

---

libraries/botbuilder-core/requirements.txt
libraries/botbuilder-dialogs/requirements.txt
libraries/botframework-connector/requirements.txt

chore: Cryptograhphy to 41.0.4

---

libraries/botbuilder-applicationinsights/setup.py

chore: django to 3.2.20

---

libraries/functional-tests/functionaltestbot/setup.py

chore: flask to 2.2.5

---

libraries/botbuilder-applicationinsights/setup.py

chore: django to 3.2.21

---

libraries/botbuilder-integration-aiohttp/botbuilder/integration/aiohttp/__init__.py

Exporting ConfigurationBotFrameworkAuthentication

---

libraries/botbuilder-dialogs/setup.py

Dialogs: regex version bump

---

.pylintrc
libraries/botbuilder-applicationinsights/django_tests/tests.py
old.pylintrc
pipelines/botbuilder-python-ci.yml

fixes: https://github.com/microsoft/teams-ai/issues/679

Python 3.11 Pylint

---

libraries/botbuilder-applicationinsights/setup.py
libraries/botbuilder-core/botbuilder/core/teams/teams_info.py
libraries/botbuilder-core/tests/teams/test_teams_activity_handler.py
libraries/botbuilder-integration-applicationinsights-aiohttp/botbuilder/integration/applicationinsights/aiohttp/aiohttp_telemetry_middleware.py

djangorestframework bump

---

libraries/botbuilder-applicationinsights/setup.py

django to 3.2.24

---

libraries/botbuilder-applicationinsights/django_tests/views.py

Test correction for SM01307

---

libraries/botframework-connector/botframework/connector/auth/government_constants.py

Corrected Gov LoginUrl prefix

---

libraries/botbuilder-schema/botbuilder/schema/_models_py3.py

#minor 
add `properties` to `ChannelAccount` model to match js/dotnet impls.
https://github.com/microsoft/botbuilder-js/blob/main/libraries/botframework-schema/src/index.ts#L162
https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Schema/ChannelAccount.cs#L55

add `properties` to `ChannelAccount`

---

libraries/botbuilder-azure/botbuilder/azure/cosmosdb_storage.py

Added CosmosDB warning: Use CosmosDbPartitionedStorage instead.

---

libraries/botbuilder-adapters-slack/botbuilder/adapters/slack/slack_helper.py
libraries/botbuilder-ai/botbuilder/ai/luis/luis_recognizer.py
libraries/botbuilder-ai/botbuilder/ai/luis/luis_recognizer_v2.py
libraries/botbuilder-ai/botbuilder/ai/luis/luis_recognizer_v3.py
libraries/botbuilder-ai/botbuilder/ai/qna/dialogs/qnamaker_dialog.py
libraries/botbuilder-ai/botbuilder/ai/qna/models/ranker_types.py
libraries/botbuilder-ai/botbuilder/ai/qna/qnamaker.py
libraries/botbuilder-ai/botbuilder/ai/qna/utils/train_utils.py
libraries/botbuilder-core/botbuilder/core/bot_framework_adapter.py
libraries/botbuilder-core/botbuilder/core/cloud_adapter_base.py
libraries/botbuilder-core/botbuilder/core/inspection/inspection_middleware.py
libraries/botbuilder-core/botbuilder/core/skills/_skill_handler_impl.py
libraries/botbuilder-core/botbuilder/core/telemetry_logger_middleware.py
libraries/botbuilder-core/botbuilder/core/turn_context.py
libraries/botbuilder-core/tests/skills/test_skill_handler.py
libraries/botbuilder-core/tests/teams/test_teams_activity_handler.py
libraries/botbuilder-dialogs/botbuilder/dialogs/_user_token_access.py
libraries/botbuilder-dialogs/botbuilder/dialogs/dialog_context.py
libraries/botbuilder-dialogs/botbuilder/dialogs/dialog_extensions.py
libraries/botbuilder-dialogs/botbuilder/dialogs/dialog_manager.py
libraries/botbuilder-dialogs/botbuilder/dialogs/memory/dialog_state_manager.py
libraries/botbuilder-dialogs/botbuilder/dialogs/prompts/oauth_prompt.py
libraries/botbuilder-dialogs/botbuilder/dialogs/skills/skill_dialog.py
libraries/botbuilder-dialogs/tests/test_dialog_manager.py
libraries/botbuilder-integration-aiohttp/botbuilder/integration/aiohttp/bot_framework_http_client.py
libraries/botbuilder-integration-aiohttp/botbuilder/integration/aiohttp/skills/aio_http_client_factory.py
libraries/botbuilder-integration-aiohttp/tests/skills/test_skill_http_client.py
libraries/botframework-connector/botframework/connector/auth/certificate_app_credentials.py
libraries/botframework-connector/botframework/connector/auth/government_constants.py
libraries/botframework-connector/tests/test_skill_validation.py

Fixes https://github.com/microsoft/BotBuilder-Samples/issues/3933

fix: Corrections for errors in Skill Dialogs

---

libraries/botbuilder-ai/setup.py
libraries/botbuilder-integration-aiohttp/setup.py
libraries/botbuilder-integration-applicationinsights-aiohttp/setup.py

bump: aiohttp to 3.9.4 in SDK packages

---

libraries/botbuilder-core/botbuilder/core/cloud_adapter_base.py

Parity in CloudAdapterBase.update_activity to use correct activity id

---

libraries/botframework-connector/botframework/connector/auth/skill_validation.py

Fixes #2116 
Correct valid tenant specific token issuers.

fix populating token issuers

---

generators/app/templates/echo/{{cookiecutter.bot_name}}/bot.py

Fixes #2123
Resolved the inconsistency in response formats between the Python Echo bot template and the C# and JavaScript Echo bot templates. 
The Python Echo bot template now matches the response format of the C# and JavaScript bots.

Resolved the inconsistency in response formats between the Python Echo bot template and the C# and JavaScript Echo bot templates.

---

libraries/botbuilder-ai/setup.py
libraries/botbuilder-integration-aiohttp/setup.py
libraries/botbuilder-integration-applicationinsights-aiohttp/setup.py

aiohttp 3.9.5

---

libraries/botbuilder-integration-aiohttp/botbuilder/integration/aiohttp/configuration_service_client_credential_factory.py

Fix for ConfigurationServiceClientCredentialFactory to allow auth disabled scenario

---

libraries/botbuilder-adapters-slack/botbuilder/adapters/slack/slack_helper.py
libraries/botbuilder-core/botbuilder/core/adapters/test_adapter.py
libraries/botbuilder-core/tests/test_bot_framework_adapter.py
libraries/botbuilder-core/tests/test_conversation_state.py
libraries/botbuilder-core/tests/test_memory_transcript_store.py
libraries/botbuilder-core/tests/test_private_conversation_state.py
libraries/botbuilder-core/tests/test_telemetry_middleware.py
libraries/botbuilder-core/tests/test_test_adapter.py
libraries/botbuilder-core/tests/test_user_state.py
libraries/botbuilder-dialogs/botbuilder/dialogs/choices/channel.py
libraries/botbuilder-dialogs/tests/choices/test_channel.py
libraries/botbuilder-dialogs/tests/memory/scopes/test_memory_scopes.py
libraries/botbuilder-dialogs/tests/test_dialog_manager.py
libraries/botframework-connector/botframework/connector/channels.py
libraries/botframework-connector/tests/test_attachments.py
libraries/botframework-connector/tests/test_attachments_async.py
libraries/botframework-connector/tests/test_conversations.py
libraries/botframework-connector/tests/test_conversations_async.py

Fixes #1438
- Adding directlinespeech & test channels in channels.py
- Replacing hardcoded channel names with references from the Channels Enum

Adding directlinespeech & test channels in channels.py

---

libraries/botbuilder-adapters-slack/requirements.txt
libraries/botbuilder-ai/setup.py
libraries/botbuilder-integration-aiohttp/setup.py
libraries/botbuilder-integration-applicationinsights-aiohttp/setup.py

#minor
Updates `aiohttp `from 3.10.2 to 3.10.5
https://github.com/microsoft/botbuilder-python/pull/2157

bump: aiohttp from 3.10.2 to 3.10.5

---

libraries/botbuilder-core/botbuilder/core/cloud_adapter_base.py

Fixed ExpectReplies response
